#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_FY00) += fy00_clk.o
obj-$(CONFIG_TARGET_FY10D) += fy00_clk.o
obj-$(CONFIG_TARGET_FY10DS) += fy00_clk.o
obj-$(CONFIG_TARGET_FY01) += fy01_clk.o
obj-$(CONFIG_TARGET_FY02) += fy02_clk.o
obj-$(CONFIG_TARGET_FY02B) += fy02b_clk.o
obj-$(CONFIG_TARGET_FY02P) += fy02p_clk.o
obj-$(CONFIG_TARGET_FY10P) += fy10p_clk.o
obj-$(CONFIG_TARGET_FY12) += fy12_clk.o
obj-$(CONFIG_TARGET_XC01) += xc01_clk.o
obj-$(CONFIG_ARCH_MOLCHIP) += mc_clk.o
