/*
 * Copyright (c) 2016-2017 Linaro Ltd.
 * Copyright (c) 2016-2022 Molchip Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef __DTS_XC_CLOCK_H
#define __DTS_XC_CLOCK_H

/* fixed rate clocks PLL*/
#define	XTL			0	
#define	RTC			1
#define	DPLL		2	
#define	PLL_DIV2	3
#define	PLL_DIV3	4
#define	PLL_DIV4	5
#define	PLL_DIV5	6
#define	PLL_DIV6	7
#define	PLL_DIV7	8
#define	PLL_1000_1	9
#define	PLL_990		10
#define	PLL_667_1	11
#define	PLL_667_2	12
#define	PLL_667_3	13
#define	PLL_667_4	14
#define	PLL_500_1	15
#define	PLL_400_1	16
#define	PLL_286_1	17
#define	PLL_200_2	18
#define	SPLL_DIV2	19
#define	SPLL_DIV3	20
#define	SPLL_DIV4	21
#define	SPLL_DIV5	22
#define	SPLL_DIV6	23
#define	SPLL_DIV7	24
#define	SPLL_425_1	25
#define	SPLL_594_1	26
#define	SPLL_743_1	27
#define	DSI_PHY		28
#define	CSI_PHY		29
#define	CLK_RC		30	
#define	RC_DIV4		31
#define	EPHY_REF	32

/* fixed factor PLLDIV*/
#define	CLK_XTL_24			0
#define	CLK_XTL_1        	1
#define	CLK_32K          	2
#define	CLK_PLL_500      	3
#define	CLK_PLL_250      	4
#define	CLK_PLL_125      	5
#define	CLK_PLL_333_5    	6
#define	CLK_PLL_66_7     	7
#define	CLK_PLL_400	     	8
#define	CLK_PLL_200	     	9
#define	CLK_PLL_100	     	10
#define	CLK_PLL_80		 	11
#define	CLK_PLL_50		 	12
#define	CLK_PLL_25		 	13
#define	CLK_PLL_20		 	14
#define	CLK_PLL_286	     	15
#define	CLK_PLL_500_05	 	16
#define	CLK_PLL_250_025  	17
#define	CLK_PLL_990	     	18
#define	CLK_PLL_667_1	 	19
#define	CLK_PLL_333_6	 	20
#define	CLK_PLL_333_65	 	21
#define	CLK_PLL_667_4	 	22
#define	CLK_PLL_500_1	 	23
#define	CLK_PLL_400_1	 	24
#define	CLK_PLL_200_2	 	25
#define	CLK_PLL_286_1	 	26
#define	CLK_SPLL_45	     	27
#define	CLK_SPLL_297	 	28
#define	CLK_SPLL_148_5	 	29
#define	CLK_SPLL_74_25	 	30
#define	CLK_SPLL_27	     	31
#define	CLK_SPLL_425_1	 	32
#define	CLK_SPLL_594_1	 	33
#define	CLK_SPLL_743_1	 	34
#define	CLK_RC_200_1	 	35
#define	CLK_RC_24_1	     	36

/*top sys gate */
#define	CKG_PTS_EN					0
#define	CKG_GLB_AON_CPU_EN			1
#define	CKG_GLB_AON_ISP_EN			2
#define	CKG_GLB_AON_VEU_EN			3
#define	CKG_ARC600_0_EN			 	4
#define	CKG_ARC600_1_EN			 	5
#define	CKG_DMA1_EN				 	6
#define	CKG_GLB_APB_DMC_EN			7
#define	CKG_GLB_APB_VOU_EN			8
#define	CKG_GLB_APB_NNP_EN			9
#define	CKG_GLB_APB_VEU_EN			10
#define	CKG_GLB_APB_ISP_EN			11
#define	CKG_APB_WDT0_EN			 	12
#define	CKG_APB_WDT1_EN			 	13
#define	CKG_APB_SYST_EN			 	14
#define	CKG_SYST_EN				 	15
#define	CKG_APB_UART3_EN			16
#define	CKG_UART3_EN				17
#define	CKG_APB_UART2_EN			18
#define	CKG_UART2_EN				19
#define	CKG_APB_RTCT_EN			 	20
#define	CKG_APB_GPIO_EN			 	21
#define	CKG_APB_TIMER0_EN			22
#define	CKG_APB_TIMER1_EN			23
#define	CKG_APB_TIMER2_EN			24
#define	CKG_APB_I2C2_EN			 	25
#define	CKG_I2C2_EN				 	26
#define	CKG_APB_INT_CTRL_EN		 	27
#define	CKG_WDT_EN					28
#define	CKG_XTL_TMR0_EN			 	29
#define	CKG_RTC_TMR0_EN			 	30
#define	CKG_XTL_TMR1_EN			 	31
#define	CKG_RTC_TMR1_EN			 	32
#define	CKG_XTL_TMR2_EN			 	33
#define	CKG_RTC_TMR2_EN			 	34
#define	CKG_GPIO_DEBOUCE_EN		 	35
#define	CKG_CAM_IF_EN				36
#define	CKG_SENSOR0_EN				37
#define	CKG_SENSOR1_EN				38
#define	CKG_SENSOR2_EN				39
#define	CKG_PMU_EN					40
#define	CKG_DEB_EN					41
#define	CKG_DVPIN_DLLREF_EN		 	42
#define	CKG_BUSMON_TIMER_EN		 	43
#define	CKG_AUX0_EN				 	44
#define	CKG_APB_C2C_CA7_TO_ARC0_EN	45
#define	CKG_APB_C2C_ARC0_TO_CA7_EN	46
#define	CKG_APB_C2C_CA7_TO_ARC1_EN	47
#define	CKG_APB_C2C_ARC1_TO_CA7_EN	48
#define	CKG_APB_C2C_ARC0_TO_ARC1_EN 49
#define	CKG_APB_C2C_ARC1_TO_ARC0_EN 50
#define CKG_APB_NNP_EN				51
#define CKG_NNP_EN					52
#define CKG_VDSP_EN					53 
#define CKG_MUX_NNP_P				54
#define CKG_MUX_AI_BUS_P			55
#define CKG_MUX_VDSP_CORE_P			56
#define CKG_MUX_VEU_SYS_P			57

/*cpu sys*/
#define CKG_CA7_CORE_EN			0
#define CKG_CPU_DBG_EN		    1
#define DAP_EN				    2
#define CKG_DMA0_EN		        3
#define CKG_AES_EN			    4
#define CKG_AHB_RNG_EN		    5
#define CKG_AHB_HSLOCK_EN	    6
#define CKG_AHB_IROM_EN	        7
#define CKG_APB_RSA_EN		    8
#define CKG_RSA_EN			    9
#define CKG_APB_HASH_EN	        10
#define CKG_HASH_EN		        11
#define CKG_APB_SRC_EN		    12
#define CKG_SRC_EN			    13
#define CKG_APB_I2C0_EN	        14
#define CKG_I2C0_EN		        15
#define CKG_APB_I2C1_EN	        16
#define CKG_I2C1_EN		        17
#define CKG_APB_I2C3_EN	        18
#define CKG_I2C3_EN		        19
#define CKG_APB_UART0_EN	    20
#define CKG_UART0_EN		    21
#define CKG_APB_UART1_EN	    22
#define CKG_UART1_EN		    23
#define CKG_APB_DMIC0_EN	    24
#define CKG_DMIC0_EN		    25
#define CKG_APB_DMIC1_EN	    26
#define CKG_DMIC1_EN		    27
#define CKG_APB_GPIO_CLK_EN	    28
#define CKG_APB_I2S0_EN	        29
#define CKG_APB_I2S1_EN	        30
#define CKG_APB_SPI0_EN	        31
#define CKG_SPI0_EN		        32
#define CKG_APB_SPI1_EN	        33
#define CKG_SPI1_EN		        34
#define CKG_APB_PWM_EN		    35
#define CKG_PWM_EN			    36
#define CKG_APB_MOTORCTL0_EN    37
#define CKG_APB_MOTORCTL1_EN    38
#define CKG_APB_EFUSE_EN	    39
#define CKG_EFUSE_EN		    40
#define CKG_APB_DAP_EN		    41
#define CKG_GPIO_DEBOUCE_CLK_EN 42
#define CKG_MOTORCTL0_STM_EN    43
#define CKG_MOTORCTL1_STM_EN    44
#define CKG_I2S0_SLOW_EN	    45
#define CKG_I2S0_FAST_EN	    46
#define CKG_I2S0_FRAC_DIV_EN    47
#define CKG_I2S1_SLOW_EN	    48
#define CKG_I2S1_FAST_EN	    49
#define CKG_I2S1_FRAC_DIV_EN    50
#define CKG_MUX_DMIC0			51
#define CKG_MUX_DMIC1			52
#define CKG_MUX_MOTORCTL0_DB	53
#define CKG_MUX_MOTORCTL1_DB	54
#define CKG_MUX_I2S0_SLOW_PAD	55
#define CKG_MUX_I2S0_SLOW		56
#define CKG_MUX_I2S0_FAST		57
#define CKG_MUX_I2S0_SOURCE	    58
#define CKG_MUX_I2S1_SLOW_PAD	59
#define CKG_MUX_I2S1_SLOW		60
#define CKG_MUX_I2S1_FAST		61
#define CKG_MUX_I2S1_SOURCE		62

/*cpucomposite_mux_clks*/
#define CKG_MUX_CA7_CORE		0
#define CKG_MUX_RSA		        1
#define CKG_MUX_HASH		    2
#define CKG_MUX_SRC		        3
#define CKG_MUX_SPI0		    4
#define CKG_MUX_SPI1		    5
#define CKG_MUX_PWM		        6
#define CKG_MUX_CS_DBG		    7
#define CKG_MUX_EFUSE_PAD	    8
#define CKG_MUX_EFUSE		    9
#define CKG_MUX_I2C0			10
#define CKG_MUX_I2C1			11
#define CKG_MUX_I2C3			12
#define CKG_MUX_UART0		    13
#define CKG_MUX_UART1		    14
#define CKG_MUX_GPIO_DEBOUCE	15
#define CKG_MUX_MOTORCTL0_STM	16
#define CKG_MUX_MOTORCTL1_STM	17

/*isp sys gate*/
#define	CKG_CSI_CFG_EN			 	0
#define	CKG_EPHY_REF_EN		     	1
#define	CKG_IR_EN				 	2
#define	CKG_AHB_VPU_EN			 	3
#define	CKG_VPU_EN				 	4
#define	CKG_VICAP_EN			 	5
#define	CKG_AHB_2DLUT_EN		 	6
#define	CKG_2DLUT_EN			 	7
#define	CKG_AHB_ISP_EN			 	8
#define	CKG_ISP_EN				 	9
#define	CKG_APB_USB3_CFG_EN	    	10
#define	CKG_APB_DPHYRX_PCS_EN	 	11
#define	CKG_APB_GMAC1_CSR_EN	 	12
#define	CKG_AXI_USB3_EN		     	13
#define	CKG_AXI_GMAC1_EN		 	14
#define	CKG_CSI_4L_APB_EN		 	15
#define	CKG_CSI_2L_APB_EN		 	16
#define	CKG_MIPI0_ADAPTER_EN	 	17
#define	CKG_MIPI0_ADAPTER_APB_EN	18
#define	CKG_MIPI1_ADAPTER_EN	 	19
#define	CKG_MIPI1_ADAPTER_APB_EN	20
#define	CKG_USB3_SUSPEND_EN	     	21
#define	CKG_USB32_REF_EN		 	22
#define	CKG_GMAC1_TX_EN		     	23
#define	CKG_GMAC1_RX_EN		    	24
#define	CKG_GMAC1_RMII_EN		 	25
#define CKG_MUX_IR					26
#define CKG_MUX_ISP_BUS		    	27
#define CKG_MUX_VPU			    	28
#define CKG_MUX_VICAP		    	29
#define CKG_MUX_CSI_CFG				30
#define CKG_MUX_USB3_SUSPEND		31	
#define CKG_MUX_USB32_REF			32
#define CKG_MUX_GMAC1_RMII_PAD			33

/*nnp sys gate*/
#define CKG_VPPU400_EN 0

/*veu sys */
#define CKG_VENC460_EN			0
#define CKG_LZMA_CORE_EN		1
#define CKG_EMMC_2X_EN			2
#define CKG_EMMC_EN			    3
#define CKG_AHB_EMMC_EN		    4
#define CKG_EMMC_BASE_EN		5
#define CKG_EMMC_CQETM_EN		6
#define CKG_EMMC_TM_EN			7
#define CKG_SDIO0_EN			8
#define CKG_AHB_SDIO0_EN		9
#define CKG_SDIO0_DLLREF_EN	    10
#define CKG_SDIO1_EN			11
#define CKG_AHB_SDIO1_EN		12
#define CKG_SDIO1_DLLREF_EN	    13
#define CKG_SFC_EN				14
#define CKG_APB_SFC_EN			15
#define CKG_SADCW_EN			16
#define CKG_EPHY0_REF_EN		17
#define CKG_APB_EPHY_PHYCFG_EN	18
#define CKG_APB_EMMC_PHYCFG_EN	19
#define CKG_APB_AUDIO_CODEC_EN	20
#define CKG_APB_PTS_EN			21
#define CKG_APB_SADC_EN		    22
#define CKG_APB_GMAC0_CSR_EN	23
#define CKG_AHB_JPG_EN			24
#define CKG_JPG_EN				25
#define CKG_AHB_ISP460_EN		26
#define CKG_ISP460_EN			27
#define CKG_APB_ENC_BUF_CTRL_EN 28
#define CKG_AXI_EMMC_EN		    29
#define CKG_AXI_GMAC0_EN		30
#define CKG_IOE_PUB_EN			31
#define CKG_IOE_CH0_EN			32
#define CKG_GMAC0_TX_EN		    33
#define CKG_GMAC0_RX_EN		    34
#define CKG_GMAC0_RMII_EN       35
#define CKG_MUX_SDIO0			36
#define CKG_MUX_SDIO1			37
#define CKG_MUX_VENC460			38
#define CKG_MUX_VENC460_SLOW    39
#define CKG_MUX_LZMA_CORE	    40
#define CKG_MUX_EMMC_2X		    41
#define CKG_MUX_EMMC_CQETM	    42
#define CKG_MUX_EMMC_TM		    43
#define CKG_MUX_SFC			    44
#define CKG_MUX_SADCW			45
#define CKG_MUX_EMMC_1X			46

/*vou sys */
#define CKG_APB_DPHY_CFG_EN 0
#define CKG_APB_DSI_CFG_EN	1
#define CKG_AHB_VGS_EN		2
#define CKG_VGS_EN			3
#define CKG_G2D_EN			4
#define CKG_VDEC460_EN		5
#define CKG_VOU400_EN		6
#define CKG_MUX_VGS			7

/*top composite clks*/
#define CKG_MUX_PTS			0
#define CKG_MUX_SYST		1	
#define CKG_MUX_UART3		2
#define CKG_MUX_UART2		3
#define CKG_MUX_I2C2		4	
#define CKG_MUX_GPIO_DEBOUC	5
#define CKG_MUX_CAM_IF		6
#define CKG_MUX_SENSOR0		7
#define CKG_MUX_SENSOR1		8
#define CKG_MUX_SENSOR2		9
#define CKG_MUX_GLB_APB_CFG	10
#define CKG_MUX_GLB_AON_CFG	11
#define CKG_MUX_VOU_BUS		12
#define CKG_MUX_PMU_CFG		13
#define CKG_MUX_DEB_CFG		14
#define CKG_MUX_DVPIN_DLLREF_CFG		15


#endif