#ifndef _REGISTER_LIST_H_
#define _REGISTER_LIST_H_

#define GLOBAL_BASE					0x00000000
#define DSD_CHN_BASE				0x00001000
#define DHD0_CHN_BASE				0x00004000
#define DHD1_CHN_BASE				0x00008000
#define HTV_ENC_BASE				0x00000E00
#define CVBS_BASE					0X00000F00
#define DHD0_CHN_COEF_BASE			0x00000000
#define DHD1_CHN_COEF_BASE			0x00000600


/*VOU global register offset*/
#define VOU_VERSION_ID_OFFSET			0x00
#define VOU_DSD_CK_EB_OFFSET			0x10	//VOU_CHN_CK_EB_OFFSET
#define VOU_DHD0_CK_EB_OFFSET			0x14
#define VOU_DHD1_CK_EB_OFFSET			0x18
#define VOU_VGA_SRC_OFFSET				0x20
#define VOU_HDMI_SRC_OFFSET				0x24
#define VOU_AXI_CFG_OFFSET				0x40
#define VOU_AXI_STS_OFFSET				0x44
#define VOU_AXI_CH_STS0_OFFSET			0x48
#define VOU_AXI_CH_STS1_OFFSET			0x4C
#define DHD_DISPLAY_FORMAT_OFFSET		0x50

#define ARQOS_LOW_OFFSET				0x60
#define ARQOS_HIGH_OFFSET				0x64
#define ARQOS_THR_LOW_OFFSET			0x68
#define ARQOS_THR_HIGH_OFFSET			0x6c
#define AWQOS_LOW_OFFSET				0x70
#define AWQOS_HIGH_OFFSET				0x74
#define AWQOS_THR_LOW_OFFSET			0x78
#define AWQOS_THR_HIGH_OFFSET			0x7c
#define RCH_URGENCY_CNT_CLR_OFFSET		0x80
#define WCH_URGENCY_CNT_CLR_OFFSET		0x84
#define RCH_URGENCY_CNT_OFFSET			0x88
#define WCH_URGENCY_CNT_OFFSET			0x8C
#define VOU_PERF_CFG_OFFSET				0xA0
#define VOU_ECO_CK_EB_OFFSET			0xF8
#define VOU_ECO_REG_OFFSET				0xFC

/*VOU channel register offset*/

#define CHN_INT_STS_OFFSET   			0x00
#define CHN_INT_MASK_OFFSET  			0x04
#define CHN_INT_CLR_OFFSET  			0x08
#define CHN_INT_RAW_OFFSET 				0x0C
#define CHN_VGA_EB_OFFSET   			0x10
#define CHN_HDMI_EB_OFFSET  			0x14
#define CHN_WBC_CLR_OFFSET  			0x18
#define CHN_IDLE_STS_OFFSET 			0x1C
#define CHN_UPDATE_CTRL0_OFFSET 		0x20
#define CHN_UPDATE_CTRL1_OFFSET  		0x24
#define CHN_UPDATE_CTRL2_OFFSET  		0x28
#define CHN_FORCE_UPDATE_OFFSET 		0x2C
#define CHN_UPDATE_MODE_OFFSET  		0x30
#define CHN_WORK_CTRL_OFFSET  			0x34
#define CHN_MINOR_CTRL_OFFSET 			0x38
#define CHN_UPDATE_STS0_OFFSET 			0x40
#define CHN_UPDATE_STS1_OFFSET  		0x44
#define CHN_UPDATE_STS2_OFFSET  		0x48
#define CHN_CFG_OFFSET  				0x100
#define CHN_LAYER_ORDER_OFFSET  		0x104
#define CHN_CLIP_INFO_OFFSET  			0x108
#define BG_INFO_YUV_OFFSET   			0x10C
#define ACTIVE_INFO_OFFSET   			0x110
#define HBLANK_INFO_OFFSET   			0x114
#define TF_BLANK_INFO_OFFSET 			0x118
#define BF_BLANK_INFO_OFFSET 			0x11C
#define TESTMODE_CFG_OFFSET     		0x120
#define CHESS_INFO_OFFSET    			0x124
#define BG_INFO_RGB_OFFSET   			0x128

/* 0x40 ~ 0x5C: color bar information*/
#define COLOR_BAR_INFO0_OFFSET			0x130
#define COLOR_BAR_INFO1_OFFSET			0x134
#define COLOR_BAR_INFO2_OFFSET			0x138
#define COLOR_BAR_INFO3_OFFSET			0x13c
#define COLOR_BAR_INFO4_OFFSET			0x140
#define COLOR_BAR_INFO5_OFFSET			0x144
#define COLOR_BAR_INFO6_OFFSET			0x148
#define COLOR_BAR_INFO7_OFFSET			0x14c

#define CSC_MATRIX_COEFF0_OFFSET		0x150
#define CSC_MATRIX_COEFF1_OFFSET		0x154
#define CSC_MATRIX_COEFF2_OFFSET		0x158
#define CSC_MATRIX_OFFSET_OFFSET		0x15C

#define IMG_RIM_WIDTH_OFFSET      		0x160
#define IMG_RIM_COLOR0_OFFSET     		0x164
#define IMG_RIM_COLOR1_OFFSET     		0x168
#define IMG0_CFG_OFFSET					0x180
#define IMG1_CFG_OFFSET					0x190
#define HDMI_CFG_OFFSET					0x1A0
#define DHD_DISPLAY_CFG_OFFSET			0x1A4
#define DHD_DISPLAY_DELAY_OFFSET		0x1A8
#define V0_SCCOEF_ADDR_OFFSET			0x1B0
#define WBC_SCCOEF_ADDR_OFFSET			0x1B8

#define WBC_CFG_OFFSET               	0x200
#define WBC_Y_BASE_ADDR_OFFSET       	0x204
#define WBC_UV_BASE_ADDR_OFFSET     	0x208
#define WBC_CROP_SRC_START_OFFSET 		0x20c
#define WBC_CROP_DES_SIZE_OFFSET     	0x210
#define WBC_SCALER_DES_SIZE_OFFSET		0x214

/* 0x300 ~ 0x300 + 0x1C: HC ctrl registers*/
#define HC_BASE_OFFSET               	0x300
#define OSD_BASE_OFFSET              	0x400
/* 0x400 ~ 0x400 + 0x1C: OSD ctrl register*/
#define GUI_CTRL_OFFSET              	0x000
#define GUI_ALPHA_PARA_OFFSET        	0x004
#define GUI_SRC_START_OFFSET         	0x008
#define GUI_SRC_SIZE_OFFSET          	0x00C
#define GUI_SRC_PITCH_OFFSET        	0x010
#define GUI_BASE_ADDR_OFFSET         	0x014
#define GUI_DES_START_OFFSET         	0x018

/* 0x500 ~ 0x500 + 0x30: video imageV1 ctrl registers*/
#define IMG1_OFFSET         			0x500
/* 0x1000 ~ 0x1000 + 0x3FC: video imageV0 ctrl registers*/
#define IMG0_OFFSET						0x1000

/*offset based on IMG0_OFFSET or IMG1_OFFSET*/
#define IMG_BX_CTRL_OFFSET            	0x00
#define IMG_BX_SRC_START_OFFSET       	0x04
#define IMG_BX_SRC_SIZE_OFFSET        	0x08
#define IMG_BX_SRC_PITCH_OFFSET       	0x0C
#define IMG_BX_Y_BASE_ADDR_OFFSET     	0x10
#define IMG_BX_C_BASE_ADDR_OFFSET    	0x14
#define IMG_BX_DES_START_OFFSET       	0x18
#define IMG_BX_DES_SIZE_OFFSET        	0x1C
#define IMG_BX_CM_PARA0_OFFSET        	0x20
#define IMG_BX_CM_PARA1_OFFSET        	0x24
#define IMG_BX_CM_PARA2_OFFSET        	0x28
#define IMG_BX_CM_PARA3_OFFSET        	0x2C
#define IMG_BX_CTRL_OFFSET_STEP        	0x40


#define FETCH_SC_COEFF_H_Y_TAB_OFFSET   0x000
#define FETCH_SC_COEFF_H_C_TAB_OFFSET   0x100
#define FETCH_SC_COEFF_V_Y_TAB_OFFSET   0x180

#define WBC_SC_COEFF_H_Y_TAB_OFFSET     0x300
#define WBC_SC_COEFF_H_C_TAB_OFFSET     0x400
#define WBC_SC_COEFF_V_Y_TAB_OFFSET     0x480

#define TVE_CLAMP_INFO0_OFFSET			0x00		
#define TVE_CLAMP_INFO1_OFFSET			0x04
#define TVE_CLAMP_INFO2_OFFSET			0x08
#define TVE_CLAMP_INFO3_OFFSET			0x0c
#define TVE_SYNC_CFG_OFFSET				0x10
#define TVE_HSYNC_INFO_OFFSET			0x14
#define TVE_VSYNC_INFO0_OFFSET			0x18	
#define TVE_VSYNC_INFO1_OFFSET			0x1c
#define TVE_FIR_CFG_OFFSET				0x4c	
#define DAC_CFG_OFFSET					0x50	

#define CVBS_VIDEO_FORMAT_CTRL_OFFSET	0x00
#define CVBS_VIDEO_INPUT_CTRL_OFFSET	0x04
#define CVBS_VIDEO_OUTPUT_CTRL_OFFSET	0x08
#define CVBS_POWER_DOWN_CTRL_OFFSET		0x0C
#define CVBS_SOFT_RESET_CTRL_OFFSET		0x10
#define CVBS_VIDEO_FILTER_MODE_OFFSET	0x80
#define CVBS_VIDEO_FILTER_COEF01_OFFSET	0x84
#define CVBS_VIDEO_FILTER_COEF23_OFFSET	0x88
#define CVBS_VIDEO_FILTER_COEF45_OFFSET	0x8C
#define CVBS_VIDEO_FILTER_COEF67_OFFSET	0x90
#define CVBS_VIDEO_FILTER_COEF23_OFFSET	0x88
#define CVBS_VIDEO_FILTER_COEF45_OFFSET	0x8C
#define CVBS_VIDEO_FILTER_COEF67_OFFSET	0x90
#define CVBS_VIDEO_DETECT_EN_OFFSET		0x94
#define CVBS_VIDEO_HIGH_NUM_OFFSET		0x98
#define CVBS_VIDEO_LOW_NUM_OFFSET		0x9C

#define OFFSET_CKG_CFG 					0x00
#define OFFSET_SOFT_RST_CFG 			0x14
#define OFFSET_MISC_REG0 				0x78
#define OFFSET_MISC_REG1 				0x7c

#define OFFSET_CKG_GLB_VIO_CFG 			0x30

#define APB_BASE					0X00000000

#endif
