export CONFIG_XOS_PROJECT_TYPE=esl
export CONFIG_XOS_USE_APP_NATIVE_ESL=true
#lvgl&font
export CONFIG_LVGL_VERSION=lvgl-v9
export CONFIG_XOS_EXT_FREETYPE=false
export CONFIG_XOS_USE_TINY_TTF=true

export CONFIG_XOS_FWK_APPMANAGER=true
export CONFIG_XOS_USE_APP_LAUNCHER=false
export CONFIG_XOS_USE_APP_H5_ESL=false
export CONFIG_XOS_USE_INNER_RES=true
export CONFIG_XOS_FWK_PARAM=true
export CONFIG_XOS_FWK_EFFECTS=true
export CONFIG_XOS_BASE_QM10XD=true
export CONFIG_XOS_INN_QUANTP=false
export CONFIG_XOS_FWK_PLAYER=true
export CONFIG_XOS_EXT_CJSON=true
export CONFIG_XOS_USE_DEBUG=true
export CONFIG_XOS_FWK_UTILITY=true
export CONFIG_XOS_FWK_QMCORE=true
export CONFIG_XOS_EXT_CURL=true
export CONFIG_XOS_FWK_CADP_CURL=true

export CONFIG_XOS_RES_800x1280=true
export CONFIG_XOS_EXT_JPEG=true
export CONFIG_XOS_EXT_LIBPNG=true
export CONFIG_XOS_FWK_FONT=true
export CONFIG_XOS_LCM_2ND_SCR=true
export CONFIG_XOS_EXT_ZLIB=true

export CONFIG_XOS_EXT_OPENSSL=false
export CONFIG_XOS_FWK_CADP_DSN=true

export CONFIG_XOS_FWK_CADP_QUA=true
export CONFIG_XOS_FWK_CADP=true
export CONFIG_XOS_FWK_LOGO=true
export CONFIG_XOS_LVGL_MEM_CNT=true
