#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_MOLCHIP)   += spl.o
obj-$(CONFIG_ARCH_MOLCHIP)   += spl_bootm.o
