/*
** raw_language_to_strings_map.c: This file defines the map from language to raw strings. 
**     This file is auto-generated by using `extract_strings_from_xlsx.py`.
**     Please take care when you modify this file mannually.
**
**     Copyright (c) Quaming Intelligent Technology Co., Ltd. 
**     (C) Copyright All Rights Reserved. 
**
*/

#include "lang/ime_language_ids.h"
#include "xos_language_ids.h"

#ifdef __MMI_LANGUAGE_CHINESE_CN__
extern const char* __xos_raw_strings_chinese_cn [];
#endif /* __MMI_LANGUAGE_CHINESE_CN__*/
#ifdef __MMI_LANGUAGE_ENGLISH_US__
extern const char* __xos_raw_strings_english_us [];
#endif /* __MMI_LANGUAGE_ENGLISH_US__*/

#define NULL ((void*)0)

LANGUAGE_RAW_STRINGS __xos_map_language_to_raw_strings [] = {
#ifdef __MMI_LANGUAGE_CHINESE_CN__
    {/* LANGID_CHINESE_CN, */IMELANGIDChineseSimplified, "Chinese (China)", "简体中文", __xos_raw_strings_chinese_cn},
#else
    {/*LANGID_CHINESE_CN, */IMELANGIDChineseSimplified, NULL, NULL, NULL},
#endif /* __MMI_LANGUAGE_CHINESE_CN__*/
#ifdef __MMI_LANGUAGE_ENGLISH_US__
    {/* LANGID_ENGLISH_US, */IMELANGIDEnglish, "English (USA)", "English (USA)", __xos_raw_strings_english_us},
#else
    {/*LANGID_ENGLISH_US, */IMELANGIDEnglish, NULL, NULL, NULL},
#endif /* __MMI_LANGUAGE_ENGLISH_US__*/
};

