/*
** xos_language_ids.h: This file defines the language identifiers. 
**     This file is auto-generated by using `extract_strings_from_xlsx.py`.
**     Please take care when you modify this file mannually.
**
**     Copyright (c) Quaming Intelligent Technology Co., Ltd. 
**     (C) Copyright All Rights Reserved. 
**
*/

#ifndef _XOS_LANGUAGE_IDS_H_
#define _XOS_LANGUAGE_IDS_H_

enum {
    /* 000 */ LANGID_AUTOMATIC, /* Automatic */
    /* 001 */ LANGID_CHINESE_CN, /* Chinese (China) */
    /* 002 */ LANGID_ENGLISH_US, /* English (USA) */
    MAX_LANGID, /* Not a real LANGID */
};

typedef struct _LANGUAGE_RAW_STRINGS {
    int            ime_lang_id;
    const char*    locale_name;
    const char*    self_name;
    const char**   raw_strings;
} LANGUAGE_RAW_STRINGS;

typedef struct _LANGUAGE_ZIPPED_STRINGS {
    int             ime_lang_id;
    const char*     locale_name;
    const char*     self_name;
    const char*     zipped_bytes;
    unsigned int    zipped_size;
    unsigned int    origin_size;
} LANGUAGE_ZIPPED_STRINGS;

#ifdef __cplusplus
extern "C" {
#endif

extern LANGUAGE_RAW_STRINGS __xos_map_language_to_raw_strings [];
extern LANGUAGE_ZIPPED_STRINGS __xos_map_language_to_zipped_bytes [];

#ifdef __cplusplus
}
#endif

#endif /* _XOS_LANGUAGE_IDS_H_ */

