interface=wlan0
driver=nl80211
ssid=MyAP_5G
hw_mode=a
channel=36
country_code=CN
ieee80211n=1
ieee80211ac=1
ht_capab=[HT40+][SHORT-GI-40][MAX-AMSDU-7935]
vht_capab=[MAX-MPDU-7935][SHORT-GI-80]
#vht_oper_chwidth=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=12345678
wmm_enabled=1