/*
** zipped_language_to_bytes_map.c: This file defines the map from language to zipped strings. 
**     This file is auto-generated by using `extract_strings_from_xlsx.py`.
**     Please take care when you modify this file mannually.
**
**     Copyright (c) Quaming Intelligent Technology Co., Ltd. 
**     (C) Copyright All Rights Reserved. 
**
*/

#include "lang/ime_language_ids.h"
#include "xos_language_ids.h"

#define NULL ((void*)0)

#ifdef __MMI_LANGUAGE_CHINESE_CN__
extern const char __xos_zipped_bytes_chinese_cn [];
#endif /* __MMI_LANGUAGE_CHINESE_CN__*/
#ifdef __MMI_LANGUAGE_ENGLISH_US__
extern const char __xos_zipped_bytes_english_us [];
#endif /* __MMI_LANGUAGE_ENGLISH_US__*/

LANGUAGE_ZIPPED_STRINGS __xos_map_language_to_zipped_bytes [] = {
    {/*LANGID_AUTOMATIC, */IMELANGIDNone, "Automatic", "Automatic", NULL, 0, 0},
#ifdef __MMI_LANGUAGE_CHINESE_CN__
    {/* LANGID_CHINESE_CN, */IMELANGIDChineseSimplified, "Chinese (China)", "简体中文", __xos_zipped_bytes_chinese_cn, 1700, 3234},
#else
    {/*LANGID_CHINESE_CN, */IMELANGIDChineseSimplified, NULL, NULL, NULL, 0, 0},
#endif /* __MMI_LANGUAGE_CHINESE_CN__*/
#ifdef __MMI_LANGUAGE_ENGLISH_US__
    {/* LANGID_ENGLISH_US, */IMELANGIDEnglish, "English (USA)", "English (USA)", __xos_zipped_bytes_english_us, 1785, 3536},
#else
    {/*LANGID_ENGLISH_US, */IMELANGIDEnglish, NULL, NULL, NULL, 0, 0},
#endif /* __MMI_LANGUAGE_ENGLISH_US__*/
};

