#!/bin/sh

mount -t tmpfs none /tmp
cp -rf /etc /tmp/
mount -t tmpfs none /etc
cp -rf /tmp/etc/* /etc
rm -rf /tmp/etc

#echo zstd > /sys/devices/virtual/block/zram0/comp_algorithm
echo 18M  > /sys/block/zram0/disksize
mkswap /dev/zram0
swapon /dev/zram0
echo 100 > /proc/sys/vm/swappiness
echo 2048 > /proc/sys/vm/min_free_kbytes
echo 0 >  /proc/sys/vm/watermark_boost_factor
echo 10 > /proc/sys/vm/watermark_scale_factor
#Aggressively reclaim the cache.
echo 10000 >/proc/sys/vm/vfs_cache_pressure
echo 5 > /proc/sys/vm/dirty_background_ratio
echo 10 > /proc/sys/vm/dirty_ratio
echo 0  > /proc/sys/kernel/printk_ratelimit
echo 500 | tee /proc/sys/kernel/printk_ratelimit_burst
echo on > /proc/sys/kernel/printk_devkmsg

