#!/bin/sh

# Source profile to get environment variables
. /etc/profile

FOLDER=/autorun
SCRIPT=autorun.sh

if [ -d $FOLDER ]; then
  cd $FOLDER
  if [ -f $SCRIPT ]; then
    if [ -x $SCRIPT ]; then
      ./$SCRIPT
    fi
  fi
fi

