from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

inc = [cwd + "/include"]

LIBS       = ['avcodec'] + ['avformat'] + ['avutil'] + ['swresample']
LIBPATH    = [cwd + '/rtt']

objs = DefineGroup('qxos', src, depend = [''], CPPPATH = inc, LIBPATH = LIBPATH, LIBS = LIBS)

Return('objs')
