# Makefile for Versatile-specific clocks
obj-y		+= clk.o div-mc.o gate-mc.o mux-mc.o composite-mc.o fh_common.o
obj-$(CONFIG_COMMON_CLK_MC_XC) += xc-simple-clock.o
obj-$(CONFIG_RESET_CONTROLLER) += reset.o
obj-$(CONFIG_MINI_CLK)+= mini-clock.o

