#
# Copyright (c) 2024 Quaming, Inc
#
# SPDX-License-Identifier:      GPL-2.0+
#
ifdef CONFIG_SCRIPT_CMD
obj-y += udisk_flash.o
obj-$(CONFIG_FLASH_FW_ON_KEY_PRESS) += util_flash.o
endif

obj-y += logo/
