from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

inc = [cwd + "/include"] + [cwd + "/include/libpng16"]

LIBS       = ['png16']
LIBPATH    = [cwd + '/arm']

objs = DefineGroup('qxos', src, depend = [''], CPPPATH = inc, LIBPATH = LIBPATH, LIBS = LIBS)

Return('objs')
