interface=wlan0
driver=nl80211
ssid=MyAP_2.4G
hw_mode=g
country_code=CN
channel=6
ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]
auth_algs=1
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
macaddr_acl=0
