

# The location of the leases file

#lease_file	/var/lib/misc/udhcpd.leases	#defualt: /var/lib/misc/udhcpd.leases
lease_file	/data/udhcpd.leases

# The location of the pid file
#pidfile	/var/run/udhcpd.pid	#default: /var/run/udhcpd.pid
pidfile	/data/udhcpd.pid

start 169.254.57.2
end 169.254.57.254
interface wlan0
max_leases 234
opt router 169.254.57.1

