#ifndef __VENC_DRV_IO_H__
#define __VENC_DRV_IO_H__

/******************************************************************************
    Include other header files
 *****************************************************************************/
#include "fh_venc_mpi.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* End of #ifdef __cplusplus */

/******************************************************************************
    Macros, Enums, Structures definition list
 *****************************************************************************/

typedef struct
{
    FY_S32 (*dummy)(void);
} VENC_EXPORT_FUNC_S;


/******************************************************************************
    VENC driver ioctl definition list
 *****************************************************************************/
#define VENC_IOC_MAGIC		'E'
#define IOC_VENC_INIT							_IOW(VENC_IOC_MAGIC,0,FH_VENC_DTS_CLK_ATTR)
#define IOC_VENC_DEINIT							_IO(VENC_IOC_MAGIC,1)
#define IOC_VENC_RESET_CHAN						_IOW(VENC_IOC_MAGIC,2,FY_U32)
#define IOC_VENC_BIND_CHAN						_IOW(VENC_IOC_MAGIC,3,FY_U32)
#define IOC_VENC_UNBIND_CHAN					_IO(VENC_IOC_MAGIC,4)
#define IOC_VENC_CREATE_CHAN					_IOW(VENC_IOC_MAGIC,5,FH_VENC_CHN_CAP)
#define IOC_VENC_DESTROY_CHAN					_IOW(VENC_IOC_MAGIC,6,FY_U32)
#define IOC_VENC_SET_CHAN_ATTR					_IOW(VENC_IOC_MAGIC,7,FH_VENC_SET_CHN_ATTR)
#define IOC_VENC_GET_CHAN_ATTR					_IOWR(VENC_IOC_MAGIC,8,FH_VENC_GET_CHN_ATTR)
#define IOC_VENC_START_RECIEVE_PIC				_IOW(VENC_IOC_MAGIC,9,FY_U32)
#define IOC_VENC_STOP_RECIEVE_PIC				_IOW(VENC_IOC_MAGIC,10,FY_U32)
#define IOC_VENC_SUBMIT_FRAME					_IOW(VENC_IOC_MAGIC,11,FH_VENC_SEND_STREAM)
#define IOC_VENC_GET_CHN_STREAM_TIMEOUT			_IOWR(VENC_IOC_MAGIC,12,FH_VENC_STREAM_TIMEOUT)
#define IOC_VENC_RELEASE_STREAM					_IOW(VENC_IOC_MAGIC,13,FH_VENC_STREAM)
#define IOC_VENC_CHECKADDR						_IOWR(VENC_IOC_MAGIC,14,FH_ENC_CHECK_ADDR)
#define IOC_VENC_GET_CHN_STATUS					_IOWR(VENC_IOC_MAGIC,15,FH_VENC_CHN_STATUS_ATTR)
#define IOC_VENC_GET_STREAM						_IOWR(VENC_IOC_MAGIC,16,FH_VENC_STREAM)
#define IOC_VENC_GET_STREAM_BLOCK				_IOWR(VENC_IOC_MAGIC,17,FH_VENC_STREAM_BLOCK)
#define IOC_VENC_GET_STREAM_TIMEOUT				_IOWR(VENC_IOC_MAGIC,18,FH_VENC_STREAM_TIMEOUT)
#define IOC_VENC_GET_STREAM_BUF_CONF			_IOWR(VENC_IOC_MAGIC,19,FH_VENC_STR_CON_ATTR)

#define IOC_VENC_SET_ROTATE						_IOW(VENC_IOC_MAGIC, 20,FH_VENC_ROTATE_ATTR)
#define IOC_VENC_GET_ROTATE						_IOWR(VENC_IOC_MAGIC,21,FH_VENC_ROTATE_ATTR)

#define IOC_VENC_SET_ROIMAP						_IOW(VENC_IOC_MAGIC, 22,FH_VENC_ROIMAP_ATTR)
#define IOC_VENC_SET_ROI_CFG					_IOW(VENC_IOC_MAGIC, 23,FH_VENC_ROI_ATTR)
#define IOC_VENC_CLEAR_ROI						_IOW(VENC_IOC_MAGIC, 24,FY_U32)
#define IOC_VENC_REQUEST_IDR					_IOW(VENC_IOC_MAGIC, 25,FY_U32)

#define IOC_VENC_SET_RC_ATTR					_IOW(VENC_IOC_MAGIC, 26,FH_VENC_RC_PARA_ATTR)
#define IOC_VENC_GET_RC_ATTR					_IOWR(VENC_IOC_MAGIC, 27,FH_VENC_RC_PARA_ATTR)

#define IOC_VENC_SET_RC_CHANGE					_IOW(VENC_IOC_MAGIC, 28,FH_VENC_RC_CHANGE_ATTR)

#define IOC_VENC_SET_LOST_FRAME					_IOW(VENC_IOC_MAGIC, 29,FH_VENC_DROP_ATTR)
#define IOC_VENC_GET_LOST_FRAME					_IOWR(VENC_IOC_MAGIC, 30,FH_VENC_DROP_ATTR)

#define IOC_VENC_SET_BKG_QP						_IOW(VENC_IOC_MAGIC, 31,FH_VENC_BKGQP_ATTR)
#define IOC_VENC_GET_BKG_QP						_IOWR(VENC_IOC_MAGIC, 32,FH_VENC_BKGQP_ATTR)

#define IOC_VENC_SET_ENC_PARAM					_IOW(VENC_IOC_MAGIC, 33,FH_VENC_ENCPARAM_ATTR)
#define IOC_VENC_GET_ENC_PARAM					_IOWR(VENC_IOC_MAGIC, 34,FH_VENC_ENCPARAM_ATTR)

#define IOC_VENC_SET_H264_ENTROPY				_IOW(VENC_IOC_MAGIC, 35,FH_VENC_H264ENTROPY_ATTR)
#define IOC_VENC_GET_H264_ENTROPY				_IOWR(VENC_IOC_MAGIC, 36,FH_VENC_H264ENTROPY_ATTR)

#define IOC_VENC_SET_H264_DBLK					_IOW(VENC_IOC_MAGIC, 37,FH_VENC_H264DBLK_ATTR)
#define IOC_VENC_GET_H264_DBLK					_IOWR(VENC_IOC_MAGIC, 38,FH_VENC_H264DBLK_ATTR)

#define IOC_VENC_SET_H264_SLICE_SPLIT			_IOW(VENC_IOC_MAGIC, 39,FH_VENC_H264SLICE_SPLIT_ATTR)
#define IOC_VENC_GET_H264_SLICE_SPLIT			_IOWR(VENC_IOC_MAGIC, 40,FH_VENC_H264SLICE_SPLIT_ATTR)

#define IOC_VENC_SET_H265_ENTROPY				_IOW(VENC_IOC_MAGIC, 41,FH_VENC_H265ENTROPY_ATTR)
#define IOC_VENC_GET_H265_ENTROPY				_IOWR(VENC_IOC_MAGIC, 42,FH_VENC_H265ENTROPY_ATTR)

#define IOC_VENC_SET_H265_DBLK					_IOW(VENC_IOC_MAGIC, 43,FH_VENC_H265DBLK_ATTR)
#define IOC_VENC_GET_H265_DBLK					_IOWR(VENC_IOC_MAGIC, 44,FH_VENC_H265DBLK_ATTR)

#define IOC_VENC_SET_H265_SLICE_SPLIT			_IOW(VENC_IOC_MAGIC, 45,FH_VENC_H265SLICE_SPLIT_ATTR)
#define IOC_VENC_GET_H265_SLICE_SPLIT			_IOWR(VENC_IOC_MAGIC, 46,FH_VENC_H265SLICE_SPLIT_ATTR)

#define IOC_VENC_SET_DEBREATH_EFFECT			_IOW(VENC_IOC_MAGIC, 47,FH_VENC_DEBREATH_ATTR)
#define IOC_VENC_GET_DEBREATH_EFFECT			_IOWR(VENC_IOC_MAGIC, 48,FH_VENC_DEBREATH_ATTR)

#define IOC_VENC_CLEAR_YUV_QUEUE				_IOW(VENC_IOC_MAGIC, 49, FY_U32)

#define IOC_VENC_SET_BIAS						_IOW(VENC_IOC_MAGIC, 50,FH_VENC_BIAS_ATTR)
#define IOC_VENC_GET_BIAS						_IOWR(VENC_IOC_MAGIC, 51,FH_VENC_BIAS_ATTR)

#define IOC_VENC_SET_DRV_CFG					_IOW(VENC_IOC_MAGIC, 52,FH_VENC_SET_DRV_CONFIG)
#define IOC_VENC_SET_SWITCH_ATTR				_IOW(VENC_IOC_MAGIC,53,FH_VENC_SET_SWITCH_ATTR)
#define IOC_VENC_SET_DUMP_ATTR					_IOW(VENC_IOC_MAGIC,54,FH_VENC_DUMP_ATTR)
#define IOC_VENC_SET_EX_ATTR					_IOW(VENC_IOC_MAGIC,55,FH_VENC_EX_ATTR)


//Others IOC is not supported confirmed by FW.



#define IOC_TYPE_VENC 'e'

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif //__VENC_DRV_IO_H__
