#ifndef __MOLCHIP_LT00_H__
#define __MOLCHIP_LT00_H__

#define REG_SPI1_BASE			(0x08A00000)
#define REG_SPI0_BASE			(0x08B00000)
#define REG_UART0_BASE			(0x08F00000)
#define REG_UART1_BASE			(0x09000000)
#define REG_UART2_BASE			(0x09100000)
#define REG_CPU_SYS_CLK_RF_BASE		(0x09200200)
#define REG_TIMER0_BASE			(0x09800000)
#define REG_SYS_TIMER_BASE		(0x09700000)
#define REG_EFUSE_BASE			(0x0A700000)
#define REG_CPU_SYS_PIN_REG_BASE	(0x0B100000)
#define REG_PTS_BASE			(0x0B800000)
#define REG_CPU_SYS_AHB_REG_BASE	(0x0C000000)
#define REG_AES_BASE			(0x0C600000)
#define REG_DMA_BASE			(0x0C700000)
#define REG_SDIO0_BASE			(0x0C900000)
#define REG_GLB_APB_BASE		(0x10000000)
#define REG_CEN_PIN_REG_BASE		(0x10200000)
#define REG_TOP_CLK_RF_BASE		(0x10300200)
#define REG_DMC_SYS_APB_REG_BASE	(0x24000000)
#define REG_DMC_SYS_PIN_REG_BASE	(0x25B00000)
#define REG_SDIO1_BASE			(0x25E00000)
#define REG_SPIC_BASE			(0x26400000)
#define REG_SPIC_CFG_BASE		REG_SPIC_BASE

#define REG_CPLL_CTRL0			(REG_CPU_SYS_AHB_REG_BASE + 0x00)
#define CKG_SYST_EN			(BIT(1))
#define CKG_XTL_TMR_EN			(BIT(4))
#define CKG_RTC_TMR_EN			(BIT(3))

#define REG_CEN_PERI_CLK_CTRL		(REG_CPU_SYS_AHB_REG_BASE + 0xAC)
#define CKG_APB_PTS_EN			(BIT(21))
#define CKG_UART1_EN			(BIT(10))
#define CKG_UART0_EN			(BIT(9))
#define CKG_SPI1_EN			(BIT(8))
#define CKG_SPI0_EN			(BIT(6))


#define REG_CEN_PERI_APB_CLK_CTRL	(REG_CPU_SYS_AHB_REG_BASE + 0xB0)
#define CKG_APB_SPI1_EN			(BIT(19))
#define CKG_APB_UART1_EN		(BIT(13))
#define CKG_APB_UART0_EN		(BIT(12))
#define CKG_APB_GPIO_EN			(BIT(11))
#define CKG_APB_SYST_EN			(BIT(10))
#define CKG_APB_SPI0_EN			(BIT(8))
#define CKG_APB_TIMER_EN		(BIT(2))
#define CKG_APB_EFUSE_EN		(BIT(0))

#define REG_AP_PERI_SOFT_RST0		(REG_CPU_SYS_AHB_REG_BASE + 0xB4)
#define PTS_SOFT_RST			(BIT(25))
#define SPI1_SOFT_RST			(BIT(23))
#define TIMER0_RTC_SOFT_RST		(BIT(19))
#define TIMER0_XTL_SOFT_RST		(BIT(18))
#define SPI0_SOFT_RST			(BIT(15))
#define UART1_SOFT_RST			(BIT(6))
#define UART0_SOFT_RST			(BIT(5))

#define REG_AP_PERI_SOFT_RST		REG_AP_PERI_SOFT_RST0

#define REG_PTS_RD_LOW			(REG_CPU_SYS_AHB_REG_BASE + 0xC8)
#define REG_PTS_RD_HIGH			(REG_CPU_SYS_AHB_REG_BASE + 0xCC)

#define REG_CKG_EFUSE_CTL		(REG_CPU_SYS_AHB_REG_BASE + 0xE0)
#define CKG_EFUSE_EN			(BIT(0))

#define REG_CPU_SYS_CLK_CTRL		(REG_CPU_SYS_AHB_REG_BASE + 0x1C0)
#define CKG_PTS_EN			(BIT(0))

#define REG_SFC_CTRL0			(REG_DMC_SYS_APB_REG_BASE + 0xE38)
#define CKG_SFC_EN			(BIT(0))
#define CKG_APB_SFC_EN			(BIT(2))
#define SFC_SOFT_RST			(BIT(16))
#define SFC_CLOCK_SEL(val)		(((val) & 0x7) << 4)

#define REG_DMA_CTRL			(REG_CPU_SYS_AHB_REG_BASE + 0x1c)
#define CKG_DMA0_EN			(BIT(1))

#define REG_DMA0_REG			(REG_CPU_SYS_AHB_REG_BASE + 0x20)
#define DMA_SOFT_RST			(BIT(23))
#define STRAP_PIN_STATUS		(REG_GLB_APB_BASE + 0x104)
#define get_strap_status()		__raw_readl(STRAP_PIN_STATUS)

//DMA CID defination
#define SPIC_RX_RID			12
#define SPIC_TX_RID			13
#define SPIC_RX1_RID			26
#define UART0_RX_RID			0
#define UART1_RX_RID			2
#define UART2_RX_RID			18

#define REG_SYS_TIMER_VALUE		(REG_SYS_TIMER_BASE + 0xc)
#define get_sys_timer_val()		__raw_readl(REG_SYS_TIMER_VALUE)

#define CLK_UART0_CFG			(REG_CPU_SYS_CLK_RF_BASE + 0x50)

/*sdio ctrl & pin fun_sel&pull&drive strenth*/
#define SD_0_SEL_PAD_2

#define REG_SDIO0_CTRL0			(REG_CPU_SYS_AHB_REG_BASE + 0x214)
#define REG_SDIO0_CTRL1			(REG_CPU_SYS_AHB_REG_BASE + 0x218)
#define REG_MTX_CLK_CTRL0		(REG_CPU_SYS_AHB_REG_BASE + 0xDC)
#define REG_SDIO0_CTRL2			REG_MTX_CLK_CTRL0

#define REG_SDIO0_SPL1			(REG_CPU_SYS_AHB_REG_BASE + 0x220)
#define SDIO0_DLLOUT_STATUS_SPL		(REG_CPU_SYS_AHB_REG_BASE + 0x224)
#define SDIO0_DLLOUT_STATUS_DRV		(REG_CPU_SYS_AHB_REG_BASE + 0x230)

#define REG_SDIO1_CTRL0			(REG_DMC_SYS_APB_REG_BASE + 0xE34)
#define REG_SDIO1_CTRL1			(REG_DMC_SYS_APB_REG_BASE + 0xE10)
#define REG_SDIO1_SPL1			(REG_DMC_SYS_APB_REG_BASE + 0xE18)
#define REG_VOU_CLK_CTRL		(REG_DMC_SYS_APB_REG_BASE + 0x308)
#define REG_SDIO1_CTRL2			REG_VOU_CLK_CTRL

#define SDIO1_DLLOUT_STATUS_SPL		(REG_DMC_SYS_APB_REG_BASE + 0xE1C)
#define SDIO1_DLLOUT_STATUS_DRV		(REG_DMC_SYS_APB_REG_BASE + 0xE28)

#define AHB_SDIO_SOFT_RST		(BIT(27))

#define SDIO_SPL1_VALUE			(0x9)

#define CKG_SDIO0_EN			(BIT(3))
#define CKG_SDIO0_DLLREF_EN		(BIT(2))
#define CKG_AHB_SDIO0_EN		(BIT(1))

#define CKG_AHB_SDIO1_EN		(BIT(25))
#define CKG_SDIO1_EN			(BIT(21))
#define CKG_SDIO1_DLLREF_EN		(BIT(20))

#define REG_SDIO0_CLK_MUX		(REG_CPU_SYS_CLK_RF_BASE + 0x7c)
#define REG_SDIO1_CLK_MUX		REG_VOU_CLK_CTRL
#define SDIO0_CLK_MUX_VALUE		(0x1)
#define SDIO1_CLK_MUX_VALUE		(BIT(9))

#define SDIO_DLLBYPASS_VALUE		(BIT(2))
#define SDIO_DLLCLKSEL_VALUE		(BIT(0))

#define PAD3_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x20)
#define PAD4_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x24)
#define PAD5_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x28)
#define PAD6_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x2C)
#define PAD7_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x30)
#define PAD8_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x34)
#define PAD9_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x38)

#ifdef SD_0_SEL_PAD_2
#define PAD12_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x98)
#define PAD13_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x94)
#define PAD14_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x9C)
#define PAD15_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xA0)
#define PAD16_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xA4)
#define PAD17_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xA8)
#define PAD18_G2_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xAC)
#else
#define PAD0_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xE8)
#define PAD1_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xE4)
#define PAD2_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xDC)
#define PAD3_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xE0)
#define PAD4_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xD8)
#define PAD5_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xD4)
#define PAD6_G3_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0xC4)
#endif

#define G1_PAD3_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x18)
#define G1_PAD4_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x1C)
#define G1_PAD5_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x20)
#define G1_PAD6_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x24)
#define G1_PAD7_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x28)
#define G1_PAD8_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x2C)
#define G1_PAD9_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x30)

#define G1_PAD10_REG		(REG_DMC_SYS_PIN_REG_BASE + 0x40)

#ifdef SD_0_SEL_PAD_2
#define G2_PAD12_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x5C)
#define G2_PAD13_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x58)
#define G2_PAD14_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x60)
#define G2_PAD15_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x64)
#define G2_PAD16_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x68)
#define G2_PAD17_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x6C)
#define G2_PAD18_REG			(REG_CPU_SYS_PIN_REG_BASE + 0x70)
#else
#define G3_PAD0_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x88)
#define G3_PAD1_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x84)
#define G3_PAD2_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x7C)
#define G3_PAD3_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x80)
#define G3_PAD4_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x78)
#define G3_PAD5_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x74)
#define G3_PAD6_REG			(REG_DMC_SYS_PIN_REG_BASE + 0x64)
#endif



#ifdef SD_0_SEL_PAD_2
#define IO_MUX_SD0			(0x04)
#else
#define IO_MUX_SD0			(0x05)
#endif

#define IO_MUX_SD1			(0x00)

#ifdef SD_0_SEL_PAD_2
#define IO_SD0_CD			PAD18_G2_FUNC_SEL
#define IO_SD0_CLK			PAD17_G2_FUNC_SEL
#define IO_SD0_CMD			PAD16_G2_FUNC_SEL
#define IO_SD0_D0			PAD15_G2_FUNC_SEL
#define IO_SD0_D1			PAD14_G2_FUNC_SEL
#define IO_SD0_D2			PAD13_G2_FUNC_SEL
#define IO_SD0_D3			PAD12_G2_FUNC_SEL
#else
#define IO_SD0_CD			PAD6_G3_FUNC_SEL
#define IO_SD0_CLK			PAD0_G3_FUNC_SEL
#define IO_SD0_CMD			PAD1_G3_FUNC_SEL
#define IO_SD0_D0			PAD3_G3_FUNC_SEL
#define IO_SD0_D1			PAD2_G3_FUNC_SEL
#define IO_SD0_D2			PAD4_G3_FUNC_SEL
#define IO_SD0_D3			PAD5_G3_FUNC_SEL
#endif

#define IO_SD1_CD			PAD3_G1_FUNC_SEL
#define IO_SD1_CLK			PAD6_G1_FUNC_SEL
#define IO_SD1_CMD			PAD7_G1_FUNC_SEL
#define IO_SD1_D0			PAD5_G1_FUNC_SEL
#define IO_SD1_D1			PAD4_G1_FUNC_SEL
#define IO_SD1_D2			PAD9_G1_FUNC_SEL
#define IO_SD1_D3			PAD8_G1_FUNC_SEL


#define PULL_UP(reg_val)		((reg_val & (~(0x3 << 1))) | (1 << 1))
#define DRI_STRENGTH(reg_val, strength)	((reg_val & (~(0x7 << 5))) | \
					((strength & 0x7) << 5))
#ifdef SD_0_SEL_PAD_2
#define DRI_PULL_UP_SD0_CD		G2_PAD18_REG
#define DRI_PULL_UP_SD0_CLK		G2_PAD17_REG
#define DRI_PULL_UP_SD0_CMD		G2_PAD16_REG
#define DRI_PULL_UP_SD0_D0		G2_PAD15_REG
#define DRI_PULL_UP_SD0_D1		G2_PAD14_REG
#define DRI_PULL_UP_SD0_D2		G2_PAD13_REG
#define DRI_PULL_UP_SD0_D3		G2_PAD12_REG
#else
#define DRI_PULL_UP_SD0_CD		G3_PAD6_REG
#define DRI_PULL_UP_SD0_CLK		G3_PAD0_REG
#define DRI_PULL_UP_SD0_CMD		G3_PAD1_REG
#define DRI_PULL_UP_SD0_D0		G3_PAD3_REG
#define DRI_PULL_UP_SD0_D1		G3_PAD2_REG
#define DRI_PULL_UP_SD0_D2		G3_PAD4_REG
#define DRI_PULL_UP_SD0_D3		G3_PAD5_REG
#endif

#define DRI_PULL_UP_SD1_CD		G1_PAD3_REG
#define DRI_PULL_UP_SD1_CLK		G1_PAD6_REG
#define DRI_PULL_UP_SD1_CMD		G1_PAD7_REG
#define DRI_PULL_UP_SD1_D0		G1_PAD5_REG
#define DRI_PULL_UP_SD1_D1		G1_PAD4_REG
#define DRI_PULL_UP_SD1_D2		G1_PAD9_REG
#define DRI_PULL_UP_SD1_D3		G1_PAD8_REG

/*SFC pin fun sel*/
#define PAD10_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x48)
#define PAD11_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x54)
#define PAD12_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x4C)
#define PAD13_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x44)
#define PAD14_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x40)
#define PAD15_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x3C)
#define PAD16_G1_FUNC_SEL		(REG_CEN_PIN_REG_BASE + 0x50)

#define REG_CKG_CA7_CORE_CFG		(REG_CPU_SYS_CLK_RF_BASE + 0x20)
#define CKG_CA7_CORE_SEL_OFFSET		0
#define CKG_CA7_CORE_SEL_MASK		7

#define REG_CKG_PTS_CFG			(REG_CPU_SYS_CLK_RF_BASE + 0xB8)
#define CKG_PTS_DIV_SHIFT		8
#define CKG_PTS_DIV_MASK		0x3F
#define CKG_PTS_SEL_SHIFT		0
#define CKG_PTS_SEL_MASK		3

#define GMAC_CFG_BASE			(REG_CPU_SYS_AHB_REG_BASE + 0x1D4)
#define GMAC_CTRL0_BASE			(REG_CPU_SYS_AHB_REG_BASE + 0x1DC)
#define GMAC_CTRL1_BASE			(REG_CPU_SYS_AHB_REG_BASE + 0x1E0)
#define CKG_EPHY_REF_EN			(REG_CPU_SYS_AHB_REG_BASE + 0x1FC)
#define CKG_AXI_GMAC0_EN		(BIT(0))
#define CKG_GMAC0_CSR_EN		(BIT(1))
#define AXI_GMAC0_CLK_EN		(BIT(20))
#define GMAC0_RMII_EN			(BIT(1))
#define GMAC0_RX_EN			(BIT(5))
#define GMAC0_TX_EN			(BIT(9))
#define CKG_EPHY0_REF_EN		(BIT(2))
#define CKG_APB_PHYCFG_EN		(BIT(3))
#define ANA_CTRL_EPHY_RESET		(BIT(4))
#endif/*__MOLCHIP_LT00_H__*/
