#ifndef __SW_BONDING_OPTION_H__
#define __SW_BONDING_OPTION_H__


#define SW_BOND_RSA_BIT			(1U << 31)
#define SW_BOND_AES_BIT			(1 << 30)
#define SW_BOND_SEC_MODE_MASK		(0x3)
#define SW_BOND_SEC_MODE_SHIFT		(30)
#define SW_BOND_SEC_MODE(block)		(((block) >> SW_BOND_SEC_MODE_SHIFT) & SW_BOND_SEC_MODE_MASK)
#define SW_BOND_HEADER_SEC_BIT		(1 << 29)

#define SW_BOND_EMMC_CLK_SEL_MASK	(0x3)
#define SW_BOND_EMMC_CLK_SEL_SHIFT	(22)
#define SW_BOND_EMMC_CLK_SEL(block)	(((block) >> SW_BOND_EMMC_CLK_SEL_SHIFT) & SW_BOND_EMMC_CLK_SEL_MASK)

#define SW_BOND_IF_CLK_SEL_MASK		(0x3)
#define SW_BOND_IF_CLK_SEL_SHIFT	(20)
#define SW_BOND_IF_CLK_SEL(block)	(((block) >> SW_BOND_IF_CLK_SEL_SHIFT) & SW_BOND_IF_CLK_SEL_MASK)

#define SW_BOND_SOC_FREQ_MASK		(0x3)
#define SW_BOND_SOC_FREQ_SHIFT		(17)
#define SW_BOND_SOC_FREQ(block)		(((block) >> SW_BOND_SOC_FREQ_SHIFT) & SW_BOND_SOC_FREQ_MASK)
#define SW_BOND_EXT_VOLT_BIT		(1 << 16)


#define SW_BOND_SFC_BAUD_MASK		(0x3)
#define SW_BOND_SFC_BAUD_SHIFT		(11)
#define SW_BOND_SFC_BAUD(block)		(((block) >> SW_BOND_SFC_BAUD_SHIFT) & SW_BOND_SFC_BAUD_MASK)

#define SW_BOND_VALUE_MASK		(0x7)
#define SW_BOND_VALUE_SHIFT		(13)
#define SW_BOND_WATCHDOG_SEL_BIT				(1 << 10)
#define SW_BOND_WATCHDOG_LOAD_VALUE(block)	(((block) >> SW_BOND_VALUE_SHIFT) & SW_BOND_VALUE_MASK)

#define SW_BOND_EMMC_BASECLK_SEL_BIT	(1 << 9)
#define SW_BOND_EMMC_TXCLK_POL_BIT	(1 << 8)
#define SW_BOND_EMMC_CMDCLK_POL_BIT	(1 << 7)
#define SW_BOND_EMMC_RXCLK_POL_BIT	(1 << 6)

#define SW_BOND_EMMC_IMAGE_SIZE_MASK	(0x3)
#define SW_BOND_EMMC_IMAGE_SIZE_SHIFT	(4)
#define SW_BOND_EMMC_IMAGE_SIZE(block)	(((block) >> SW_BOND_EMMC_IMAGE_SIZE_SHIFT) & SW_BOND_EMMC_IMAGE_SIZE_MASK)
#define SW_BOND_EMMC_BAUD_MASK		(0x3)
#define SW_BOND_EMMC_BAUD_SHIFT		(2)
#define SW_BOND_EMMC_BUAD(block)	(((block) >> SW_BOND_EMMC_BAUD_SHIFT) & SW_BOND_EMMC_BAUD_MASK)
#define SW_BOND_EMMC_TIMEOUT_MASK	(0x3)
#define SW_BOND_EMMC_TIMEOUT_SHIFT	(0)
#define SW_BOND_EMMC_TIMEOUT(block)	(((block) >> SW_BOND_EMMC_TIMEOUT_SHIFT) & SW_BOND_EMMC_TIMEOUT_MASK)
#define SW_BOND_SDIO_SAMPLING_MASK	(1)
#define SW_BOND_SDIO_SAMPLING_SHIFT	(19)
#define SW_BOND_SDIO_SAMPLING(block)	(((block) >> SW_BOND_SDIO_SAMPLING_SHIFT) & SW_BOND_SDIO_SAMPLING_MASK)

#endif
