#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_MOLCHIP)   += board.o 

obj-$(CONFIG_ARCH_MOLCHIP)   += aes_drv.o
obj-$(CONFIG_ARCH_MOLCHIP)   += aes.o
obj-$(CONFIG_ARCH_MOLCHIP)   += secure.o
obj-$(CONFIG_ARCH_MOLCHIP)   += spi_nor_boot.o
obj-$(CONFIG_ARCH_MOLCHIP)   += efuse_drv.o
obj-$(CONFIG_ARCH_MOLCHIP)   += bond_option.o
obj-$(CONFIG_ARCH_MOLCHIP)   += efuse.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += bignum.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += mc_hw_rsa.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += rsa.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += hash.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += sha256.o
obj-$(CONFIG_ARCH_MOLCHIP)   += system.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += lzma.o
obj-$(CONFIG_ARCH_MOLCHIP)   += nor_flash.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += string.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += sched.o
#obj-$(CONFIG_ARCH_MOLCHIP)   += pkcs5.o
