#
# Copyright (c) 2024 Quaming, Inc
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += qua_logo_core.o qua_logo_welcome.o qua_boot_gpio.o qua_boot_args.o
obj-$(CONFIG_QUA_LOGO_PART) += resource_img.o
obj-$(CONFIG_QUA_LOGO_MIPI_JD9365D) += qua_logo_mipi_jd9365d.o
obj-$(CONFIG_QUA_LOGO_RGB_EK79001H) += qua_logo_rgb_ek79001h.o
