# Project CFLAGS Configuration
#
# Common definitions for all projcts
#

ifneq ($(BUILD_PROJECT),)
	XOS_APP_ENTRY=$(word 1,$(subst _, ,$(strip $(BUILD_PROJECT))))
	ifdef CONFIG_XOS_APP_MAIN_ENTRY
		CFLAGS += -DCONFIG_XOS_APP_MAIN_ENTRY=$(CONFIG_XOS_APP_MAIN_ENTRY)
	else
		CFLAGS += -DCONFIG_XOS_APP_MAIN_ENTRY=$(XOS_APP_ENTRY)
	endif
endif

ifeq ($(CONFIG_XOS_USE_APP_LAUNCHER),true)
CFLAGS += -DCONFIG_XOS_USE_APP_LAUNCHER=1
endif

ifeq ($(CONFIG_XOS_FWK_APPMANAGER),true)
CFLAGS += -DCONFIG_XOS_FWK_APPMANAGER=1
endif

ifeq ($(CONFIG_XOS_USE_APP_STATUS_BAR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_STATUS_BAR=1
endif

ifeq ($(CONFIG_XOS_USE_APP_ANALOG_CLOCK),true)
CFLAGS += -DCONFIG_XOS_USE_APP_ANALOG_CLOCK=1
CFLAGS += -DXOS_USE_APP_ANALOG_CLOCK=1
endif

ifeq ($(CONFIG_XOS_LVGL_MEM_CNT),true)
CFLAGS += -DCONFIG_XOS_LVGL_MEM_CNT=1
endif

ifeq ($(CONFIG_XOS_USE_APP_DIGITAL_CLOCK),true)
CFLAGS += -DCONFIG_XOS_USE_APP_DIGITAL_CLOCK=1
CFLAGS += -DXOS_USE_APP_DIGITAL_CLOCK=1
endif

ifeq ($(CONFIG_XOS_USE_APP_LAYER_DEMO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_LAYER_DEMO=1
CFLAGS += -DXOS_USE_APP_LAYER_DEMO=1
endif

ifeq ($(CONFIG_XOS_USE_APP_AUDIO_PLAYER),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AUDIO_PLAYER=1
endif

ifeq ($(CONFIG_XOS_APP_XIAOMING),true)
CFLAGS += -DCONFIG_XOS_APP_XIAOMING=1
endif

ifeq ($(CONFIG_XOS_USE_APP_BOOT_ANIMATE),true)
CFLAGS += -DCONFIG_XOS_USE_APP_BOOT_ANIMATE=1
CFLAGS += -DXOS_USE_APP_BOOT_ANIMATE=1
endif

ifeq ($(CONFIG_XOS_USE_APP_DEMOAPP),true)
CFLAGS += -DCONFIG_XOS_USE_APP_DEMOAPP=1
endif

ifeq ($(CONFIG_XOS_USE_APP_DEMOLIST),true)
CFLAGS += -DCONFIG_XOS_USE_APP_DEMOLIST=1
endif

ifeq ($(CONFIG_XOS_USE_APP_COFFEE_MILL),true)
CFLAGS += -DCONFIG_XOS_USE_APP_COFFEE_MILL=1
endif

ifeq ($(CONFIG_XOS_USE_APP_CAMERA),true)
CFLAGS += -DCONFIG_XOS_USE_APP_CAMERA=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SPHOTO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SPHOTO=1
endif

ifeq ($(CONFIG_XOS_USE_APP_HEALTH),true)
CFLAGS += -DCONFIG_XOS_USE_APP_HEALTH=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTOX_RD),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTOX_RD=1
endif

ifeq ($(CONFIG_XOS_USE_APP_GALLERY),true)
CFLAGS += -DCONFIG_XOS_USE_APP_GALLERY=1
endif
ifeq ($(CONFIG_XOS_USE_APP_FRAMEO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_FRAMEO=1
endif

ifeq ($(CONFIG_XOS_IMAGEVIEWER_ACC),true)
CFLAGS += -DCONFIG_XOS_IMAGEVIEWER_ACC=1
endif

ifeq ($(CONFIG_XOS_USE_APP_FACE_RECOGNIZE),true)
CFLAGS += -DCONFIG_XOS_USE_APP_FACE_RECOGNIZE=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SETTING),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SETTING=1
endif

ifeq ($(CONFIG_XOS_APP_SETTING_PAD),true)
CFLAGS += -DCONFIG_XOS_APP_SETTING_PAD=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SMART_DOOR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SMART_DOOR=1
endif

ifeq ($(CONFIG_XOS_USE_APP_COOLFLORID),true)
CFLAGS += -DCONFIG_XOS_USE_APP_COOLFLORID=1
endif

ifeq ($(CONFIG_XOS_USE_APP_QETV),true)
CFLAGS += -DCONFIG_XOS_USE_APP_QETV=1
endif

ifeq ($(CONFIG_XOS_USE_APP_NATIVE_ESL),true)
CFLAGS += -DCONFIG_XOS_USE_APP_NATIVE_ESL=1
endif

ifeq ($(CONFIG_XOS_APP_ESL2),true)
CFLAGS += -DCONFIG_XOS_APP_ESL2=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTO=1
ifeq ($(CONFIG_XOS_USE_APP_MOTO_DASH),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTO_DASH=1
endif
ifeq ($(CONFIG_XOS_USE_APP_MOTO_CAR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTO_CAR=1
endif
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTOX),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTOX=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTOX102D),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTOX102D=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTOX7IN),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTOX7IN=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MOTOT),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOTOT=1
endif

ifeq ($(CONFIG_XOS_USE_APP_AICAMERA),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AICAMERA=1
ifeq ($(CONFIG_XOS_USE_APP_AIOBJ),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AIOBJ=1
endif
ifeq ($(CONFIG_XOS_USE_APP_AIOCR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AIOCR=1
endif
ifeq ($(CONFIG_XOS_USE_APP_PHOTO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_PHOTO=1
endif
ifeq ($(CONFIG_XOS_USE_APP_VIDEO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_VIDEO=1
endif
endif

ifeq ($(CONFIG_XOS_USE_APP_AICHAT),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AICHAT=1
endif

ifeq ($(CONFIG_XOS_USE_APP_MORESETTING),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MORESETTING=1
endif

ifeq ($(CONFIG_XOS_USE_APP_DEMO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_DEMO=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SCANPEN),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SCANPEN=1
endif

ifeq ($(CONFIG_XOS_USE_APP_LOTTIEDEMO),true)
CFLAGS += -DCONFIG_XOS_USE_APP_LOTTIEDEMO=1
CFLAGS += -DXOS_USE_APP_LOTTIEDEMO=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SMARTHOME),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SMARTHOME=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SMARTHOME_NEW),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SMARTHOME_NEW=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SETUPWIZARD),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SETUPWIZARD=1
CFLAGS += -DXOS_USE_APP_SETUPWIZARD=1
endif

ifeq ($(CONFIG_XOS_USE_LVGL_DEMOS),true)
CFLAGS += -DCONFIG_XOS_USE_LVGL_DEMOS=1
endif

ifeq ($(CONFIG_XOS_EXT_FREETYPE),true)
CFLAGS += -DCONFIG_XOS_EXT_FREETYPE=1
endif

ifeq ($(CONFIG_XOS_EXT_JPEG),true)
CFLAGS += -DCONFIG_XOS_EXT_JPEG=1
endif

ifeq ($(CONFIG_XOS_USE_CAMERA),true)
CFLAGS += -DCONFIG_XOS_USE_CAMERA=1
endif

ifeq ($(CONFIG_XOS_FWK_OTA_UART),true)
CFLAGS += -DCONFIG_XOS_FWK_OTA_UART=1
endif

ifeq ($(CONFIG_XOS_USE_FB_DIRECT),true)
CFLAGS += -DCONFIG_XOS_USE_FB_DIRECT
endif

ifeq ($(CONFIG_XOS_FWK_PLAYER),true)
CFLAGS += -DCONFIG_XOS_FWK_PLAYER=1
endif

ifeq ($(CONFIG_RESOLUTION_800x480),true)
CFLAGS += -DCONFIG_RESOLUTION_800x480=1
endif

ifeq ($(CONFIG_RESOLUTION_240x320),true)
CFLAGS += -DCONFIG_RESOLUTION_240x320=1
endif

ifeq ($(CONFIG_RESOLUTION_320x480),true)
CFLAGS += -DCONFIG_RESOLUTION_320x480=1
endif

ifeq ($(CONFIG_RESOLUTION_128x160),true)
CFLAGS += -DCONFIG_RESOLUTION_128x160=1
endif

ifeq ($(CONFIG_RESOLUTION_320x240),true)
CFLAGS += -DCONFIG_RESOLUTION_320x240=1
endif

ifeq ($(CONFIG_RESOLUTION_1280x800),true)
CFLAGS += -DCONFIG_RESOLUTION_1280x800=1
endif

ifeq ($(CONFIG_LVGL_VERSION),lvgl-v9)
CFLAGS += -DCONFIG_LVGL_V9=1
endif

ifeq ($(CONFIG_XOS_USE_TINY_TTF),true)
CFLAGS += -DCONFIG_XOS_USE_TINY_TTF=1
endif

ifeq ($(CONFIG_XOS_USE_INNER_RES),true)
CFLAGS += -DCONFIG_XOS_USE_INNER_RES=1
endif

ifeq ($(CONFIG_XOS_USE_TJPG),true)
CFLAGS += -DCONFIG_XOS_USE_TJPG=1
endif

ifeq ($(CONFIG_XOS_PROJECT_TYPE),$(strip $(BUILD_PROJECT)))
CFLAGS += -DCONFIG_XOS_PROJECT_TYPE=\"$(strip $(BUILD_PROJECT))\"
endif

ifeq ($(CONFIG_PRODUCT_IPC),true)
CFLAGS += -DCONFIG_PRODUCT_IPC=1
endif

ifeq ($(CONFIG_PRODUCT_STUDYPILOT),true)
CFLAGS += -DCONFIG_PRODUCT_STUDYPILOT=1
endif

ifeq ($(CONFIG_XOS_USE_APP_STUDYPILOT),true)
CFLAGS += -DCONFIG_XOS_USE_APP_STUDYPILOT=1
endif

ifeq ($(CONFIG_PRODUCT_MOMOTALK),true)
CFLAGS += -DCONFIG_PRODUCT_MOMOTALK=1
endif

ifeq ($(CONFIG_PRODUCT_SMARTDOOR),true)
CFLAGS += -DCONFIG_PRODUCT_SMARTDOOR=1
endif

ifeq ($(CONFIG_XOS_USE_FW_STORE_SPINAND),true)
CFLAGS += -DCONFIG_XOS_USE_FW_STORE_SPINAND=1
endif

ifeq ($(QUA_XOS_USE_RGB_LCM_800x480),true)
CFLAGS += -DQUA_XOS_USE_RGB_LCM_800x480
endif

ifeq ($(CONFIG_XOS_LITE_MODE),true)
CFLAGS += -DCONFIG_XOS_LITE_MODE
endif

ifeq ($(CONFIG_XOS_USE_GIF),true)
CFLAGS += -DCONFIG_XOS_USE_GIF=1
endif

ifeq ($(CONFIG_XOS_USE_APP_CALENDAR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_CALENDAR
endif

ifeq ($(CONFIG_XOS_USE_APP_ALARM),true)
CFLAGS += -DCONFIG_XOS_USE_APP_ALARM
endif

ifeq ($(CONFIG_XOS_USE_APP_CALCULATOR),true)
CFLAGS += -DCONFIG_XOS_USE_APP_CALCULATOR
endif

ifeq ($(CONFIG_XOS_USE_APP_AIBOX),true)
CFLAGS += -DCONFIG_XOS_USE_APP_AIBOX=1
endif

ifeq ($(CONFIG_XOS_EXT_CJSON),true)
CFLAGS += -DCONFIG_XOS_EXT_CJSON
endif

ifeq ($(CONFIG_XOS_EXT_CURL),true)
CFLAGS += -DCONFIG_XOS_EXT_CURL
endif

ifeq ($(CONFIG_XOS_EXT_HIREDIS),true)
CFLAGS += -DCONFIG_XOS_EXT_HIREDIS
endif

ifeq ($(CONFIG_XOS_EXT_FDK_AAC),true)
CFLAGS += -DCONFIG_XOS_EXT_FDK_AAC
endif

ifeq ($(CONFIG_XOS_EXT_FFMPEG),true)
CFLAGS += -DCONFIG_XOS_EXT_FFMPEG
endif

ifeq ($(CONFIG_XOS_EXT_FREETYPE),true)
CFLAGS += -DCONFIG_XOS_EXT_FREETYPE
endif

ifeq ($(CONFIG_XOS_EXT_GIFLIB),true)
CFLAGS += -DCONFIG_XOS_EXT_GIFLIB
endif

ifeq ($(CONFIG_XOS_EXT_INIPARSER),true)
CFLAGS += -DCONFIG_XOS_EXT_INIPARSER
endif

ifeq ($(CONFIG_XOS_EXT_LIBPNG),true)
CFLAGS += -DCONFIG_XOS_EXT_LIBPNG
endif

ifeq ($(CONFIG_XOS_EXT_BROWSER),true)
CFLAGS += -DCONFIG_XOS_EXT_BROWSER
endif

ifeq ($(CONFIG_XOS_EXT_LIVE),true)
CFLAGS += -DCONFIG_XOS_EXT_LIVE
endif

ifeq ($(CONFIG_XOS_EXT_LVBINDJS),true)
CFLAGS += -DCONFIG_XOS_EXT_LVBINDJS
endif

ifeq ($(CONFIG_XOS_EXT_MXML),true)
CFLAGS += -DCONFIG_XOS_EXT_MXML
endif

ifeq ($(CONFIG_XOS_EXT_OPENCV),true)
CFLAGS += -DCONFIG_XOS_EXT_OPENCV
endif

ifeq ($(CONFIG_XOS_EXT_OPENSSL),true)
CFLAGS += -DCONFIG_XOS_EXT_OPENSSL
endif

ifeq ($(CONFIG_XOS_EXT_FVAD),true)
CFLAGS += -DCONFIG_XOS_EXT_FVAD
endif

ifeq ($(CONFIG_XOS_EXT_RLOTTIE),true)
CFLAGS += -DCONFIG_XOS_EXT_RLOTTIE
endif

ifeq ($(CONFIG_XOS_EXT_ZLIB),true)
CFLAGS += -DCONFIG_XOS_EXT_ZLIB
endif

ifeq ($(CONFIG_XOS_EXT_QRCODE),true)
CFLAGS += -DCONFIG_XOS_EXT_QRCODE
endif

ifeq ($(CONFIG_XOS_INN_QUAMISC),true)
CFLAGS += -DCONFIG_XOS_INN_QUAMISC
endif

ifeq ($(CONFIG_XOS_INN_QUANTP),true)
CFLAGS += -DCONFIG_XOS_INN_QUANTP
endif

ifeq ($(CONFIG_XOS_FWK_CADP),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP
endif

ifeq ($(CONFIG_XOS_USE_APP_VIDEO_CALL),true)
CFLAGS += -DCONFIG_XOS_USE_APP_VIDEO_CALL=1
endif
ifeq ($(CONFIG_XOS_FWK_CADP_AGORA),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_AGORA
endif
ifeq ($(CONFIG_XOS_USE_APP_SCANNER),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SCANNER
endif

ifeq ($(CONFIG_XOS_USE_APP_MOMO_TALK),true)
CFLAGS += -DCONFIG_XOS_USE_APP_MOMO_TALK
endif

ifeq ($(CONFIG_XOS_USE_APP_CHATTER),true)
CFLAGS += -DCONFIG_XOS_USE_APP_CHATTER
endif

ifeq ($(CONFIG_XOS_FWK_CHATTER),true)
CFLAGS += -DCONFIG_XOS_FWK_CHATTER
endif

ifeq ($(CONFIG_XOS_FWK_CADP_KVS),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_KVS
CFLAGS += -DENABLE_DATA_CHANNEL
endif
ifeq ($(CONFIG_XOS_FWK_CADP_QUA),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_QUA
endif

ifeq ($(CONFIG_XOS_FWK_CADP_KUQI),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_KUQI
endif

ifeq ($(CONFIG_XOS_FWK_CADP_TENCENT),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_TENCENT
endif

ifeq ($(CONFIG_XOS_FWK_CADP_HEMENG),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_TENCENT
endif

ifeq ($(CONFIG_XOS_FWK_EFFECTS),true)
CFLAGS += -DCONFIG_XOS_FWK_EFFECTS
endif

ifeq ($(CONFIG_XOS_FWK_QUAAI),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAAI
endif

ifeq ($(CONFIG_XOS_FWK_QUACAMERA),true)
CFLAGS += -DCONFIG_XOS_FWK_QUACAMERA
endif

ifeq ($(CONFIG_XOS_FWK_QUAOCR),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAOCR
endif

ifeq ($(CONFIG_XOS_FWK_OTA_UART),true)
CFLAGS += -DCONFIG_XOS_FWK_OTA_UART
endif

ifeq ($(CONFIG_XOS_FWK_UART_SERVICE),true)
CFLAGS += -DCONFIG_XOS_FWK_UART_SERVICE
endif

ifeq ($(CONFIG_XOS_FWK_ABILITY),true)
CFLAGS += -DCONFIG_XOS_FWK_ABILITY
endif

ifeq ($(CONFIG_XOS_FWK_APPMANAGER),true)
CFLAGS += -DCONFIG_XOS_FWK_APPMANAGER
endif

ifeq ($(CONFIG_XOS_FWK_SYSMANAGER),true)
CFLAGS += -DCONFIG_XOS_FWK_SYSMANAGER
endif

ifeq ($(CONFIG_XOS_FWK_MQTTSER_MIDDLE),true)
CFLAGS += -DCONFIG_XOS_FWK_MQTTSER_MIDDLE
endif

ifeq ($(CONFIG_XOS_FWK_COMPONENTS),true)
CFLAGS += -DCONFIG_XOS_FWK_COMPONENTS
endif

ifeq ($(CONFIG_XOS_FWK_DEBUGGER),true)
CFLAGS += -DCONFIG_XOS_FWK_DEBUGGER
endif

ifeq ($(CONFIG_XOS_FWK_FINGER),true)
CFLAGS += -DCONFIG_XOS_FWK_FINGER
endif

ifeq ($(CONFIG_XOS_FWK_FLOATWINDOW),true)
CFLAGS += -DCONFIG_XOS_FWK_FLOATWINDOW
endif

ifeq ($(CONFIG_XOS_FWK_FONT),true)
CFLAGS += -DCONFIG_XOS_FWK_FONT
endif

ifeq ($(CONFIG_XOS_FWK_MENU),true)
CFLAGS += -DCONFIG_XOS_FWK_MENU
endif

ifeq ($(CONFIG_XOS_FWK_PARSER),true)
CFLAGS += -DCONFIG_XOS_FWK_PARSER
endif

ifeq ($(CONFIG_XOS_FWK_PLAYER),true)
CFLAGS += -DCONFIG_XOS_FWK_PLAYER
endif

ifeq ($(CONFIG_XOS_FWK_UTILITY),true)
CFLAGS += -DCONFIG_XOS_FWK_UTILITY
endif

ifeq ($(CONFIG_XOS_FWK_QUAAITALK),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAAITALK
endif

ifeq ($(CONFIG_XOS_FWK_QUAAITALK_RTC),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAAITALK_RTC
endif

ifeq ($(CONFIG_XOS_FWK_QUAIOTMGR),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAIOTMGR
endif

ifeq ($(CONFIG_XOS_FWK_QUAAISERVICE),true)
CFLAGS += -DCONFIG_XOS_FWK_QUAAISERVICE
endif

ifeq ($(CONFIG_XOS_FWK_GUIENG_LVGL9),true)
CFLAGS += -DCONFIG_XOS_FWK_GUIENG_LVGL9 -DCONFIG_LVGL_V9=1
endif

ifeq ($(CONFIG_XOS_FWK_DVR),true)
CFLAGS += -DCONFIG_XOS_FWK_DVR
endif

ifeq ($(CONFIG_XOS_HW_QUAMMAPI),true)
CFLAGS += -DCONFIG_XOS_HW_QUAMMAPI
endif

ifeq ($(CONFIG_XOS_TEST_RESTEST),true)
CFLAGS += -DCONFIG_XOS_TEST_RESTEST
endif

ifeq ($(CONFIG_XOS_DARK_MODE),true)
CFLAGS += -DCONFIG_XOS_DARK_MODE
endif

ifeq ($(CONFIG_XOS_USE_APP_CASTSCREEN),true)
CFLAGS += -DCONFIG_XOS_USE_APP_CASTSCREEN=1
endif

ifdef CONFIG_XOS_RTT_LVRENDER_PRIO
CONFIG_VAL := $(CONFIG_XOS_RTT_LVRENDER_PRIO)
CFLAGS += -DCONFIG_XOS_RTT_LVRENDER_PRIO="$(CONFIG_VAL)"
$(info LVRENDER_PRIO: $(CONFIG_VAL))
endif

ifeq ($(CONFIG_XOS_RES_800x1280),true)
CFLAGS += -DCONFIG_XOS_RES_800x1280=1
endif

ifeq ($(CONFIG_XOS_LCM_800x1280),true)
CFLAGS += -DCONFIG_XOS_LCM_800x1280=1
endif

ifeq ($(CONFIG_XOS_LCM_2ND_SCR),true)
CFLAGS += -DCONFIG_XOS_LCM_2ND_SCR=1
endif

ifeq ($(CONFIG_XOS_LCM_800x480),true)
CFLAGS += -DCONFIG_XOS_LCM_800x480=1
endif

ifeq ($(CONFIG_XOS_LCM_1024x600),true)
CFLAGS += -DCONFIG_XOS_LCM_1024x600=1
endif

ifeq ($(CONFIG_XOS_LCM_TYPE_SPI),true)
CFLAGS += -DCONFIG_XOS_LCM_TYPE_SPI=1
endif

ifeq ($(CONFIG_XOS_LCM_TYPE_RGB),true)
CFLAGS += -DCONFIG_XOS_LCM_TYPE_RGB=1
endif

ifeq ($(CONFIG_XOS_LCM_TYPE_MIPI),true)
CFLAGS += -DCONFIG_XOS_LCM_TYPE_MIPI=1
endif

ifeq ($(CONFIG_XOS_HW_QUADRV),true)
CFLAGS += -DCONFIG_XOS_HW_QUADRV=1
endif

ifeq ($(CONFIG_XOS_USE_DEBUG),true)
CFLAGS += -DCONFIG_XOS_USE_DEBUG=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SCREEN_PROTECT),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SCREEN_PROTECT=1
endif

ifeq ($(CONFIG_XOS_FWK_LCDSRV),true)
CFLAGS += -DCONFIG_XOS_FWK_LCDSRV=1
endif

ifeq ($(CONFIG_PRODUCT_KIDCAMERA),true)
CFLAGS += -DCONFIG_PRODUCT_KIDCAMERA=1
endif

ifeq ($(CONFIG_PRODUCT_KIDCAMERA_NOR),true)
CFLAGS += -DCONFIG_PRODUCT_KIDCAMERA_NOR=1
endif

ifeq ($(CONFIG_XOS_FWK_CADP_CURL),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_CURL
endif

ifeq ($(CONFIG_XOS_FWK_CADP_DSN),true)
CFLAGS += -DCONFIG_XOS_FWK_CADP_DSN
endif

ifeq ($(CONFIG_XOS_USE_PHYSICAL_KEY),true)
CFLAGS += -DCONFIG_XOS_USE_PHYSICAL_KEY
endif

ifeq ($(CONFIG_XOS_USE_BUTTOM_BACK),true)
CFLAGS += -DCONFIG_XOS_USE_BUTTOM_BACK
endif

ifeq ($(CONFIG_XOS_USE_TOUCH_PANEL),true)
CFLAGS += -DCONFIG_XOS_USE_TOUCH_PANEL
endif

ifeq ($(CONFIG_XOS_FWK_PARAM),true)
CFLAGS += -DCONFIG_XOS_FWK_PARAM
endif

ifeq ($(CONFIG_XOS_FWK_QMCORE),true)
CFLAGS += -DCONFIG_XOS_FWK_QMCORE
endif

ifeq ($(CONFIG_XOS_BASE_QM10XD),true)
CFLAGS += -DCONFIG_XOS_BASE_QM10XD
endif

ifeq ($(CONFIG_XOS_USE_APP_WIFIX),true)
CFLAGS += -DCONFIG_XOS_USE_APP_WIFIX=1
endif

ifeq ($(CONFIG_XOS_USE_APP_SITTINGPC),true)
CFLAGS += -DCONFIG_XOS_USE_APP_SITTINGPC=1
endif

ifeq ($(CONFIG_XOS_USE_NO_BOOTANIM),true)
CFLAGS += -DCONFIG_XOS_USE_NO_BOOTANIM
endif

ifeq ($(CONFIG_STORAGE_TYPE_SPINOR),true)
CFLAGS += -DCONFIG_STORAGE_TYPE_SPINOR
endif

ifeq ($(CONFIG_STORAGE_SIZE_16MB),true)
CFLAGS += -DCONFIG_STORAGE_SIZE_16MB
endif

ifeq ($(CONFIG_XOS_APP_MEDIA_PLAYER),true)
CFLAGS += -DCONFIG_XOS_APP_MEDIA_PLAYER=1
endif