# Molchip-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_MOLCHIP_PTS) += pts.o
obj-$(CONFIG_MOLCHIP_SYST) += mc_sys_timer.o
obj-$(CONFIG_MOLCHIP_APB_TIMER) += mc_apb_timer.o
obj-$(CONFIG_MOLCHIP_LZMA) += lzma.o
obj-$(CONFIG_MOLCHIP_WAKEUP_SOURCE) += molchip_wakeup_source.o
