#ifndef _DSI_COM_PARAM_H_
#define _DSI_COM_PARAM_H_

#include "data_type.h"
#include "lcm_com_param.h"

#ifdef __cplusplus
extern "C" {
#endif

/**---------------------------------------------------------------------------*
**                               Micro Define                                **
**----------------------------------------------------------------------------*/
#define DSI_PARAM_NUM 64

typedef enum {
    PHY0 = 0,
    PHY1,
    PHY_CORE_MAX
}phy_core_e;

typedef enum {
    DSI_PHY_WORK_NONE = 0,
    DSI_PHY0_WORK_1C2D,
    DSI_PHY1_WORK_1C2D,
    DSI_PHY0_WORK_1C4D,
    DSI_PHY_WORK_MODE_MAX
}dsi_phy_work_mode_e;

typedef enum {
    DSI_VIDEO_MODE = 0,
    DSI_CMD_MODE,
    DSI_MODE_MAX
}dsi_mode_e;

typedef enum {
    DSI_ONE_LANE = 0,
    DSI_TWO_LANE,
    DSI_THREE_LANE,
    DSI_FOUR_LANE,
    DSI_LANE_MAX
}dsi_lane_num_e;

typedef enum {
    DSI_RGB565 = 0, // 16bit cfg1
    DSI_RGB565_LOW, // 16bit cfg1
    DSI_RGB565_MID, // 16bit cfg1
    DSI_RGB666,     // 18bit cfg1
    DSI_RGB666_LOW, // 18bit cfg1
    DSI_RGB888,     // 24bit
    DSI_YUVA_422,   // 20bit YCbCr 422
    DSI_YUVC_422,   // 24bit YCbCr 422
    DSI_YUV8_422,   // 16bit YCbCr 422
    DSI_RGBAAA,     // 30bit
    DSI_RGBCCC,     // 36bit
    DSI_YUV8_420,   // 12bit YCbCr 422
    DSI_FORMAT_MAX
}dsi_format_e;

typedef enum {
    DSI_DI_GENERIC_WRITE_NONE    = 0x03,
    DSI_DI_GENERIC_WRITE_0_PARAM = 0x13,
    DSI_DI_GENERIC_WRITE_1_PARAM = 0x23,
    DSI_DI_GENERIC_WRITE_LONG    = 0x29,

    DSI_DI_DCS_READ_0_PARAM      = 0x06,
    DSI_DI_DCS_WRITE_0_PARAM     = 0x05,
    DSI_DI_DCS_WRITE_1_PARAM     = 0x15,
    DSI_DI_DCS_WRITE_LONG        = 0x39,

    DSI_DI_SET_MAX_PKT_SIZE      = 0x37,
    DSI_DI_PERIPHE_CMD_OFF       = 0x22,
    DSI_DI_PERIPHE_CMD_ON        = 0x32,

    DSI_DI_DELAY                = 0xFFFFFFFE,
    DSI_DI_END_OF_TABLE         = 0xFFFFFFFF
}mipi_dsi_di;

/**
 * return generated by the DSI Host controller driver
 */
typedef enum
{
    RTN_DSI_SUCCESS = 0,
    RTN_DSI_COLOR_CODING,
    RTN_DSI_OUT_OF_BOUND,
    RTN_DSI_OVERFLOW,
    RTN_DSI_INVALID_INSTANCE,
    RTN_DSI_INVALID_IO,
    RTN_DSI_CORE_INCOMPATIBLE,
    RTN_DSI_VIDEO_MODE,
    RTN_DSI_INVALID_COMMAND,
    RTN_DSI_INVALID_EVENT,
    RTN_DSI_INVALID_HANDLE,
    RTN_DSI_PHY_POWERUP,
    RTN_DSI_PHY_INVALID,
    RTN_DSI_PHY_FREQ_OUT_OF_BOUND,
    RTN_DSI_PHY_PLL_NOT_LOCKED,
    RTN_DSI_TIMEOUT
} dsi_rtn_t;
/**
 * Video stream type
 */
typedef enum
{
    VIDEO_NON_BURST_WITH_SYNC_PULSES = 0,
    VIDEO_NON_BURST_WITH_SYNC_EVENTS,
    VIDEO_BURST_WITH_SYNC_PULSES
}dsi_video_mode_t;

/**
 * Color coding type (depth and pixel configuration)
 */
typedef enum
{
    COLOR_CODE_16BIT_CONFIG1        =  0,
    COLOR_CODE_16BIT_CONFIG2        =  1,
    COLOR_CODE_16BIT_CONFIG3        =  2,
    COLOR_CODE_18BIT_CONFIG1        =  3,
    COLOR_CODE_18BIT_CONFIG2        =  4,
    COLOR_CODE_24BIT                =  5,
    COLOR_CODE_20BIT_YCC422_LOOSELY =  6,
    COLOR_CODE_24BIT_YCC422         =  7,
    COLOR_CODE_16BIT_YCC422         =  8,
    COLOR_CODE_30BIT                =  9,
    COLOR_CODE_36BIT                = 10,
    COLOR_CODE_12BIT_YCC420         = 11,
    COLOR_CODE_MAX
}dsi_color_coding_t;
/**
 * Events generated by the DSI Host controller
 */
typedef enum
{
    ACK_SOT_ERR = 0,
    ACK_SOT_SYNC,
    ACK_EOT_SYNC,
    ACK_ESCAPE_CMD_ERR,
    ACK_LP_TX_SYNC_ERR,
    ACK_HS_RX_TIMEOUT_ERR,
    ACK_FALSE_CONTROL_ERR,
    ACK_RSVD_DEVICE_ERR_7,
    ACK_ECC_SINGLE_BIT_ERR,
    ACK_ECC_MULTI_BIT_ERR,
    ACK_CHECKSUM_ERR,
    ACK_DSI_TYPE_NOT_RECOGNIZED_ERR,
    ACK_VC_ID_INVALID_ERR,
    ACK_INVALID_TX_LENGTH_ERR,
    ACK_RSVD_DEVICE_ERR_14,
    ACK_DSI_PROTOCOL_ERR,

    DPHY_ESC_ENTRY_ERR,
    DPHY_SYNC_ESC_LP_ERR,
    DPHY_CONTROL_LANE0_ERR,
    DPHY_CONTENTION_LP0_ERR,
    DPHY_CONTENTION_LP1_ERR,
    /* start of st1 */
    HS_CONTENTION,
    LP_CONTENTION,
    RX_ECC_SINGLE_ERR,
    RX_ECC_MULTI_ERR,
    RX_CRC_ERR,
    RX_PKT_SIZE_ERR,
    RX_EOTP_ERR,
    DPI_PLD_FIFO_FULL_ERR,
    GEN_TX_CMD_FIFO_FULL_ERR,
    GEN_TX_PLD_FIFO_FULL_ERR,
    GEN_TX_PLD_FIFO_EMPTY_ERR,
    GEN_RX_PLD_FIFO_EMPTY_ERR,
    GEN_RX_PLD_FIFO_FULL_ERR,

    DBI_TX_CMD_FIFO_FULL_ERR,
    DBI_TX_PLD_FIFO_FULL_ERR,
    DBI_RX_PLD_FIFO_EMPTY_ERR,
    DBI_RX_PLD_FIFO_FULL_ERR,
    DBI_ILLEGAL_CMD_ERR,
    DSI_MAX_EVENT
}dsi_event_t;
/**
 * DSI Host state machine states
 * Holds the mapping of D-PHY to the OS, logging I/O, and hardware access layer.
 */
typedef enum
{
    DSI_POWER_OFF = 0,
    DSI_POWER_ON,
    DSI_UN_INITED,
    DSI_INITED,
    DSI_STATUS_MAX
}dsi_status_e;

typedef enum
{
    BITS_WIDTH8_BPP_8 = 0,
    BITS_WIDTH8_BPP_12,
    BITS_WIDTH8_BPP_16,
    BITS_WIDTH8_BPP_18,
    BITS_WIDTH8_BPP_24,
    BITS_WIDTH9_BPP_18,
    BITS_WIDTH16_BPP_8,
    BITS_WIDTH16_BPP_12,
    BITS_WIDTH16_BPP_16,
    BITS_WIDTH16_BPP_18_OPT1,
    BITS_WIDTH16_BPP_18_OPT2,
    BITS_WIDTH16_BPP_24_OPT1,
    BITS_WIDTH16_BPP_24_OPT2,
}pixel_data_width_t;

typedef enum{
    BIT_COLOR_DISPLAY_16,
    BIT_COLOR_DISPLAY_18,
    BIT_COLOR_DISPLAY_24,
}color_display_t;

typedef enum {
    dsi_phy_lane_1 = 0,
    dsi_phy_lane_2,
    dsi_phy_lane_3,
    dsi_phy_lane_4,
    dsi_phy_lane_num_max
}dsi_phy_lane_num_e;

typedef struct {
    uint32_t mode;
    uint32_t lp11;
    uint32_t lp01;
    uint32_t zero;
    uint32_t prepare;
    uint32_t pre;
    uint32_t trail;
    uint32_t inittime;
    uint32_t exit;
    uint32_t post;
}dsi_phy_clane_timing_t;

typedef struct {
    uint32_t mode;
    uint32_t lp11;
    uint32_t lp01;
    uint32_t zero;
    uint32_t prepare;
    uint32_t trail;
    uint32_t inittime;
    uint32_t exit;
}dsi_phy_dlane_timing_t;

typedef struct {
    uint32_t mode;
    uint32_t taget;
    uint32_t tasure;
    uint32_t tago;
}dsi_phy_lane0_read_t;

typedef struct {
    vou_clk_t vou;
    mif_clk_t mif;
}dsi_clk_cfg_t;

typedef struct {
    dsi_phy_clane_timing_t clane;
    dsi_phy_dlane_timing_t dlane;
    dsi_phy_lane0_read_t read;
    dsi_clk_cfg_t clk;
}dsi_timing_t;

typedef struct  {
    uint32_t di;
    uint16_t count;
    uint8_t para_list[DSI_PARAM_NUM];
}dsi_setting_tab_t;

/**----------------------------------------------------------------------------*
**                         Compiler Flag                                      **
**----------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif
/**---------------------------------------------------------------------------*/
#endif
