#ifndef _DSI_PHY_V01_REG_DEF_H_
#define _DSI_PHY_V01_REG_DEF_H_

#ifdef __cplusplus
extern "C" {
#endif
/**---------------------------------------------------------------------------*
**                               Micro Define                                **
**----------------------------------------------------------------------------*/
#define DSI_DPHYTX_BASE_ADDR      (0x25D00000)

#define CLANE0_PARA0           (0x00 )
#define CLANE0_PARA1           (0x04 )
#define CLANE0_PARA2           (0x08 )
#define CLANE0_PARA3           (0x0c )
#define CLANE1_PARA0           (0x300)
#define CLANE1_PARA1           (0x304)
#define CLANE1_PARA2           (0x308)
#define CLANE1_PARA3           (0x30c)
#define DLANE0_PARA0           (0x10 )
#define DLANE0_PARA1           (0x14 )
#define DLANE0_PARA2           (0x18 )
#define DLANE0_PARA3           (0x1c )
#define DLANE0_PARA4           (0x20 )
#define DLANE1_PARA0           (0x24 )
#define DLANE1_PARA1           (0x28 )
#define DLANE1_PARA2           (0x2c )
#define DLANE1_PARA3           (0x30 )
#define DLANE2_PARA0           (0x34 )
#define DLANE2_PARA1           (0x38 )
#define DLANE2_PARA2           (0x3c )
#define DLANE2_PARA3           (0x40 )
#define DLANE2_PARA4           (0x340)
#define DLANE3_PARA0           (0x44 )
#define DLANE3_PARA1           (0x48 )
#define DLANE3_PARA2           (0x4c )
#define DLANE3_PARA3           (0x50 )
#define COMMON_PARA0           (0x54 )
#define MISC_PARA0             (0x58 )
#define MISC_PARA1             (0x358)
#define MODE_CFG               (0x360)
#define CLANE0_PARA4           (0x5c )
#define CLANE_PARA4            (0x35c)
#define CLANE_PARA5            (0x60 )
#define PCS_PHY_SYNC           (0x64 )
#define DESKEW_RCAL_MISC0      (0x68 )
#define DESKEW_RCAL_MISC1      (0x6c )
#define DESKEW_RCAL_MISC2      (0xf0 )
#define EXT_LOOP_CFG0          (0xf4 )
#define EXT_LOOP_CFG1          (0x3f4)
#define CL_DESKEW              (0xf8 )
#define PHY_PARA0              (0x70 )
#define PHY_PARA1              (0x74 )
#define PHY_PARA2              (0x78 )
#define PHY_PARA3              (0x7c )
#define PHY_PARA4              (0x80 )
#define PHY_PARA5              (0x374)
#define PHY_PARA6              (0x378)
#define PHY_PARA7              (0x37c)
#define PHY_PARA8              (0x380)
#define PHY_PARA9              (0x84 )
#define PHY_PARA10             (0x88 )
#define PHY_PARA11             (0x8c )
#define PHY_PARA12             (0x90 )
#define PHY_PARA13             (0x94 )
#define PHY_PARA14             (0x98 )
#define PHY_PARA15             (0x398)
#define PHY_PARA16             (0x9c )
#define PRBS_INFO0             (0xa0 )
#define SSC_CTRL0              (0xe0 )
#define SSC_CTRL1              (0x3e0)
#define PHY_RDY_CTRL0          (0xe4 )
#define PHY_RDY_CTRL1          (0x3e4)
#define PHY_RDY_INFO0          (0xe8 )
#define PHY_RDY_INFO1          (0x3e8)
#define PRBS_INFO1             (0xa4 )
#define PRBS_INFO2             (0xa8 )
#define PRBS_INFO3             (0xac )
#define PRBS_INFO4             (0x3ac)
#define PRBS_INFO5             (0xb0 )
#define PRBS_INFO6             (0xb4 )
#define PRBS_INFO7             (0xb8 )
#define PRBS_INFO8             (0xbc )
#define DPHY_DEBUG_CFG0        (0x100)
#define DPHY_DEBUG_CFGl        (0x104)
#define DPHY_DEBUG_CFG2        (0x108)
#define DPHY_DEBUG_CFG3        (0x10c)
#define DPHY_DEBUG_CFG4        (0x110)
#define DPHY_DEBUG_CFG5        (0x114)
#define DPHY_DEBUG_CFG6        (0x118)
#define DPHY_DEBUG_CFG7        (0x11c)
#define DPHY_DEBUG_CFG8        (0x120)
#define DPHY_DEBUG_CFG9        (0x124)
#define DPHY_STATUS_INFO0      (0x128)
#define DPHY_STATUS_INFO1      (0x12c)
#define DPHY_DEBUG0            (0x130)
#define DPHY_DEBUGl            (0x134)
#define DPHY_DEBUG2            (0x138)
#define DPHY_DEBUG3            (0x13c)
#define DPHY_DEBUG4            (0x140)
#define DPHY_DEBUGS            (0x144)
#define DPHY_DEBUG6            (0x148)
#define DPHY_DEBUG7            (0x14c)
#define DPHY_DEBUG8            (0x150)
#define DPHY_DEBUG9            (0x154)
#define DPHY_DEBUG10           (0x158)
#define DPHY_DEBUG11           (0x15c)
#define DPHY_DEBUG12           (0x160)
#define DPHY_DEBUG13           (0x164)
#define DPHY_DEBUG14           (0x168)
#define DPHY_DEBUG15           (0x16c)
#define DPHY_DEBUG16           (0x170)
#define DPHY_DEBUG17           (0x174)
#define DPHY_DEBUG18           (0x178)
#define DPHY_DEBUG19           (0x17c)
#define DPHY_DEBUG20           (0x180)
#define DPHY_DEBUG21           (0x184)
#define DPHY_DEBUG_CFG10       (0x1a0)
#define DPHY_DEBUG_CFG11       (0x1a4)
#define DPHY_DEBUG_CFG12       (0x1a8)
#define DPHY_DEBUG_CFG13       (0x1ac)
#define DPHY_DEBUG_CFG14       (0x1b0)
#define DPHY_DEBUG_CFG15       (0x1b4)
#define DPHY_DEBUG_CFG16       (0x1b8)
#define DPHY_DEBUG_CFG17       (0x1bc)
#define DPHY_DEBUG_CFG18       (0x1c0)
#define DPHY_DEBUG_CFG19       (0x1c4)
#define DPHY_DEBUG_CFG20       (0x1c8)
#define DPHY_DEBUG_CFG21       (0x1cc)
#define DPHY_DEBUG_CFG22       (0x1d0)
#define DPHY_DEBUG_CFG23       (0x1d4)
#define DPHY_DEBUG_CFG24       (0x1d8)
#define DPHY_DEBUG_CFG25       (0x1dc)
#define DPHY_DEBUG_CFG26       (0x1e0)
#define DPHY_DEBUG_CFG27       (0x1e4)
#define DPHY_DEBUG_CFG28       (0x1e8)
#define DPHY_DEBUG_CFG29       (0x1ec)
#define DPHY_DEBUG_CFG30       (0x200)
#define DPHY_DEBUG_CFG31       (0x204)
#define DPHY_DEBUG_CFG32       (0x208)
#define DPHY_STATUS_INFO2      (0x1f0)
#define DPHY_STATUS_INFO3      (0x1f4)

/**---------------------------------------------------------------------------*
**                              Data Structures                              **
**---------------------------------------------------------------------------*/

/**---------------------------------------------------------------------------*
**                              function                                     **
**---------------------------------------------------------------------------*/

/**----------------------------------------------------------------------------*
**                         Compiler Flag                                      **
**----------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif
/**---------------------------------------------------------------------------*/
#endif