/**
 * log enum, can be or
 */

 #ifndef _qm_log_mgr_h_
#define _qm_log_mgr_h_

#define QM_LOG(tag, fmt, ...) LV_LOG_USER("[" tag "][%s] " fmt, __func__, ##__VA_ARGS__)

// 在头文件中定义模块枚举
typedef enum {
    QM_LOG_MODULE_MOTO = 0,
    QM_LOG_MODULE_MOTO_NAV,
    QM_LOG_MODULE_MOTO_MAP,
    QM_LOG_MODULE_MOTO_MUSIC,
    QM_LOG_MODULE_MOTO_VIDEO,
    QM_LOG_MODULE_MOTO_GAME,
    QM_LOG_MODULE_MOTO_TRACK,
    QM_LOG_MODULE_MOTO_STATISTIC,
    QM_LOG_MODULE_MOTO_PHONE,
    QM_LOG_MODULE_MOTO_SPEED,
    QM_LOG_MODULE_MOTO_TIRE,
    QM_LOG_MODULE_MOTO_BATTERY,
    QM_LOG_MODULE_MOTO_WEATHER,
    QM_LOG_MODULE_MOTO_GEAR,
    QM_LOG_MODULE_MOTO_SKIN,
    QM_LOG_MODULE_MOTO_BOOST,
    QM_LOG_MODULE_MOTO_NFC,
    QM_LOG_MODULE_MOTO_POWER,
    QM_LOG_MODULE_MOTO_PASSWORD,
    QM_LOG_MODULE_MOTO_SHORTCUT,
    QM_LOG_MODULE_GALLERY,
    QM_LOG_MODULE_BATTERY,
    QM_LOG_MODULE_STATUSBAR,
    QM_LOG_MODULE_POWERONOFF,
    QM_LOG_MODULE_PHONE,
    QM_LOG_MODULE_MUSIC,
    QM_LOG_MODULE_COUNT
} qm_log_module_id_t;

#endif //_qm_log_mgr_h_
